// Revision content — Instructor Prep (English)
//
// IMPORTANT: this content covers general scuba diving knowledge
// (physics, physiology, equipment) common to all training agencies,
// plus the public SSI curriculum structure as confirmed on official SSI
// sources. It does NOT replace the SSI Instructor Manual, MySSI, or your
// Instructor Trainer's guidance. Precise figures (staff-to-student
// ratios, exam procedures, RDP/eRDPml tables) must be checked against
// your current official SSI materials: they change over time and are
// intentionally not reproduced here when SSI-specific or subject to
// change.

export const CATEGORIES = [
  { id: "physique", label: "Physics", icon: "🌊", color: "#1d6fa5" },
  { id: "physiologie", label: "Physiology & Accidents", icon: "🫁", color: "#c62828" },
  { id: "materiel", label: "Equipment", icon: "🤿", color: "#2e7d32" },
  { id: "planification", label: "Planning & Tables", icon: "🧭", color: "#6a4fb6" },
  { id: "environnement", label: "Environment & Safety", icon: "🌐", color: "#00838f" },
  { id: "ssi", label: "SSI Pathway & Teaching", icon: "🎓", color: "#ef6c00" },
];

export const QUESTIONS = [
  // ---------------- PHYSICS ----------------
  {
    id: "phy-01", cat: "physique",
    q: "What does Boyle's Law state, essential to understanding diving?",
    choices: [
      "At constant temperature, the product of pressure × volume of a gas stays constant (P1V1 = P2V2)",
      "The pressure of a gas mixture is the sum of the partial pressures of its components",
      "The amount of gas dissolved in a liquid is proportional to its partial pressure",
      "The volume of a gas is proportional to its temperature in Celsius",
    ],
    correct: 0,
    explanation: "Boyle's Law governs gas compression/expansion with depth: it's the basis of buoyancy, air consumption, and barotrauma.",
  },
  {
    id: "phy-02", cat: "physique",
    q: "Dalton's Law directly helps explain:",
    choices: [
      "The buoyancy of a submerged body",
      "The partial pressure of each gas in a breathing mix (e.g. calculating nitrox MOD)",
      "The speed of sound underwater",
      "Mask fogging",
    ],
    correct: 1,
    explanation: "Dalton: total pressure of a mix = sum of partial pressures. Essential for calculating the Maximum Operating Depth (MOD) in nitrox diving.",
  },
  {
    id: "phy-03", cat: "physique",
    q: "Henry's Law is the basis for which diving phenomenon?",
    choices: [
      "Nitrogen narcosis",
      "Dissolution of gases into tissues and blood, and therefore decompression theory",
      "Light refraction underwater",
      "Body heat loss",
    ],
    correct: 1,
    explanation: "Henry: the amount of gas dissolved in a liquid is proportional to that gas's partial pressure — the foundation of all decompression theory.",
  },
  {
    id: "phy-04", cat: "physique",
    q: "A diver descends in salt water. Compared to fresh water, their buoyancy is:",
    choices: [
      "The same, water density doesn't change",
      "More negative (they sink more)",
      "More positive (salt water is denser, about 1.025 kg/L vs 1.000 kg/L)",
      "Unpredictable, it only depends on temperature",
    ],
    correct: 2,
    explanation: "Because salt water is denser, it produces a stronger buoyant (Archimedes) force: generally more weight is needed in the sea than in fresh water.",
  },
  {
    id: "phy-05", cat: "physique",
    q: "In sea water, pressure increases by approximately:",
    choices: [
      "1 bar every 10 meters",
      "1 bar every 20 meters",
      "0.5 bar every 10 meters",
      "2 bars every 10 meters",
    ],
    correct: 0,
    explanation: "A widely-used teaching rule: roughly +1 bar per 10 m of seawater, on top of the 1 bar of atmospheric pressure at the surface. Check the exact values used in your course materials.",
  },
  {
    id: "phy-06", cat: "physique",
    q: "Why does air consumption (in volume at atmospheric pressure) increase with depth?",
    choices: [
      "The regulator becomes less efficient at depth",
      "The diver breathes faster by reflex",
      "Air is denser at depth: each breath consumes more gas molecules for the same lung volume",
      "Cold water reduces lung capacity",
    ],
    correct: 2,
    explanation: "At higher pressure, air is denser: the same lung volume corresponds to more gas drawn from the tank, hence increased consumption in liters/bar.",
  },
  {
    id: "phy-07", cat: "physique",
    q: "What happens to a lift bag rising to the surface uncontrolled?",
    choices: [
      "Nothing, its buoyancy stays constant",
      "It automatically deflates",
      "The air inside expands as it rises (Boyle's Law), accelerating its ascent uncontrollably",
      "It becomes neutral at the surface",
    ],
    correct: 2,
    explanation: "A classic teaching point to illustrate the dangers of Boyle's Law during an uncontrolled ascent, which also applies to the diver's own buoyancy.",
  },
  {
    id: "phy-08", cat: "physique",
    q: "Archimedes' principle, which governs buoyancy, states that:",
    choices: [
      "Any body submerged in a fluid experiences an upward force equal to the weight of the fluid it displaces",
      "The volume of a gas is inversely proportional to its pressure",
      "A gas's pressure increases with temperature",
      "Water density decreases with depth",
    ],
    correct: 0,
    explanation: "This is the physical principle explaining why a diver can be positively, negatively, or neutrally buoyant depending on displaced volume and weight.",
  },
  {
    id: "phy-09", cat: "physique",
    q: "Underwater, through a mask, objects generally appear:",
    choices: [
      "Smaller and farther than they really are",
      "Closer and larger than they really are (refraction effect)",
      "The same size and distance as in open air",
      "Always blurry, with no size effect",
    ],
    correct: 1,
    explanation: "Refraction between water and the air trapped in the mask makes objects appear about 25% closer and about 33% larger — an important point to teach students for distance estimation.",
  },
  {
    id: "phy-10", cat: "physique",
    q: "At depth, which color of the spectrum disappears first to the naked eye (without artificial light)?",
    choices: [
      "Blue",
      "Green",
      "Red",
      "Yellow",
    ],
    correct: 2,
    explanation: "Water progressively absorbs long wavelengths: red disappears first (within a few meters), then orange, then yellow... blue/green remain visible the longest.",
  },
  {
    id: "phy-11", cat: "physique",
    q: "Sound travels underwater:",
    choices: [
      "Much more slowly than in air",
      "At roughly the same speed as in air",
      "Much faster than in air (about 4 times)",
      "Sound doesn't travel underwater at all",
    ],
    correct: 2,
    explanation: "This increased speed also makes it much harder to locate where a sound is coming from underwater than at the surface — useful to know when explaining why visual/tactile signals are used instead of voice.",
  },
  {
    id: "phy-12", cat: "physique",
    q: "Why does a diver lose body heat much faster in water than in air at the same temperature?",
    choices: [
      "Water conducts heat far more efficiently than air (several dozen times faster)",
      "Water always contains less heat than air",
      "That's not true, heat loss is identical",
      "Only because of the apparent wind created by fins",
    ],
    correct: 0,
    explanation: "Water's thermal conductivity is far higher than air's, which explains the need for thermal protection (exposure suits) even in water that feels \"warm.\"",
  },
  {
    id: "phy-13", cat: "physique",
    q: "A full steel cylinder and a full aluminum cylinder of the same volume: which tends to become more buoyant at the end of a dive as it empties?",
    choices: [
      "Aluminum, which becomes positive faster as it empties of air",
      "Steel, systematically",
      "It never depends on the material",
      "Both become negative as they empty",
    ],
    correct: 0,
    explanation: "A classic weighting-management teaching point: aluminum cylinders tend to become positive at the end of a dive when empty, unlike steel which usually stays more negative — adjust based on the exact cylinder model.",
  },

  // ---------------- PHYSIOLOGY ----------------
  {
    id: "phz-01", cat: "physiologie",
    q: "Nitrogen narcosis is mainly caused by:",
    choices: [
      "A high partial pressure of nitrogen at depth",
      "A lack of oxygen",
      "A buildup of CO2 due to physical exertion",
      "The cold felt at depth",
    ],
    correct: 0,
    explanation: "Often compared to drunkenness, narcosis is linked to increased nitrogen partial pressure. Individual susceptibility varies widely — don't treat any single depth threshold as absolute.",
  },
  {
    id: "phz-02", cat: "physiologie",
    q: "Decompression sickness (DCS) mainly results from:",
    choices: [
      "An ascent that is too fast, causing nitrogen bubbles to form in tissues/blood",
      "A too-low oxygen partial pressure",
      "Excess CO2 from hypoventilation",
      "Dehydration before the dive",
    ],
    correct: 0,
    explanation: "An off-gassing process that is too fast prevents dissolved nitrogen from gradually returning to a gaseous phase, forming bubbles that can obstruct circulation or damage tissue.",
  },
  {
    id: "phz-03", cat: "physiologie",
    q: "What is the main risk of a rapid ascent while holding your breath with full lungs?",
    choices: [
      "Nitrogen narcosis",
      "Pulmonary barotrauma, which can lead to arterial gas embolism",
      "Shortness of breath",
      "Hypothermia",
    ],
    correct: 1,
    explanation: "If air cannot escape freely during ascent, gas expansion in the lungs (Boyle's Law) can cause pulmonary barotrauma, a severe and potentially fatal accident.",
  },
  {
    id: "phz-04", cat: "physiologie",
    q: "Oxygen toxicity (CNS effect / convulsions) is associated with:",
    choices: [
      "A too-low O2 partial pressure",
      "A high O2 partial pressure, typically beyond thresholds used in nitrox/tech diving",
      "Excess nitrogen only",
      "Water that is too cold",
    ],
    correct: 1,
    explanation: "This is why nitrox training emphasizes calculating the MOD (maximum operating depth) to stay below an O2 partial pressure threshold set by your agency's standards.",
  },
  {
    id: "phz-05", cat: "physiologie",
    q: "A mask squeeze is an example of:",
    choices: [
      "Descent barotrauma",
      "Ascent barotrauma",
      "Decompression sickness",
      "Narcosis",
    ],
    correct: 0,
    explanation: "On descent, if the air inside the mask isn't equalized, increasing external pressure can create a suction effect on the face and eyes.",
  },
  {
    id: "phz-06", cat: "physiologie",
    q: "A diver can't equalize their ears on descent and feels pain. What is the right response?",
    choices: [
      "Keep descending, the pain will pass",
      "Force a more intense Valsalva maneuver",
      "Ascend slightly, retry equalizing gently, never force it",
      "Remove the mask to equalize more easily",
    ],
    correct: 2,
    explanation: "A fundamental teaching principle to pass on to students: never force an equalization, ascend a little if needed, then descend more slowly.",
  },
  {
    id: "phz-07", cat: "physiologie",
    q: "Shortness of breath (dyspnea) while diving is most often triggered by:",
    choices: [
      "Excessive physical exertion and CO2 buildup",
      "Excessive cold alone",
      "A high nitrogen partial pressure",
      "Dehydration",
    ],
    correct: 0,
    explanation: "Exertion combined with inadequate breathing causes CO2 buildup, creating a feeling of suffocation that can become self-sustaining through panic if poorly managed.",
  },
  {
    id: "phz-08", cat: "physiologie",
    q: "As a future instructor, what is the teaching priority when a student starts becoming out of breath?",
    choices: [
      "Rush them to the surface in a panic as fast as possible",
      "Stabilize them, establish visual and physical contact, slow their breathing, stop the exertion before considering next steps",
      "Ignore it, it resolves itself",
      "Remove their regulator so they can breathe more easily",
    ],
    correct: 1,
    explanation: "Managing a student's stress and breathlessness is a central point of the group-management/rescue modules in instructor training.",
  },
  {
    id: "phz-09", cat: "physiologie",
    q: "Among these ear equalization techniques, which one is commonly taught in diving (besides Valsalva)?",
    choices: [
      "The Frenzel maneuver",
      "The Heimlich maneuver",
      "Forced abdominal breathing",
      "Pinching the mask only",
    ],
    correct: 0,
    explanation: "The Frenzel technique (using the tongue/glottis to push air toward the Eustachian tubes) is an alternative to Valsalva, often presented as gentler on the ears.",
  },
  {
    id: "phz-10", cat: "physiologie",
    q: "Deliberate hyperventilation before a breath-hold descent is dangerous because it can cause:",
    choices: [
      "A blackout (loss of consciousness) from lowered CO2, without enough warning before the oxygen runs low",
      "A beneficial increase in heart rate",
      "Better oxygenation with no risk at all",
      "Just a mild headache, nothing serious",
    ],
    correct: 0,
    explanation: "By artificially lowering CO2 (the breathing urge signal) without significantly raising available oxygen, hyperventilation delays the urge to breathe and can cause a hypoxic blackout with no warning sign.",
  },
  {
    id: "phz-11", cat: "physiologie",
    q: "Carbon monoxide poisoning (contaminated air, e.g. a badly positioned compressor) can cause:",
    choices: [
      "Headaches, confusion, nausea, potentially up to loss of consciousness",
      "Only a slight cough with no other symptom",
      "No detectable symptom before the accident occurs",
      "A temporary improvement in alertness",
    ],
    correct: 0,
    explanation: "This is why it matters for a future instructor to know good compressor-placement practices and the warning signs to watch for in students.",
  },
  {
    id: "phz-12", cat: "physiologie",
    q: "The presence of a patent foramen ovale (PFO) in a diver is a factor associated with:",
    choices: [
      "An increased risk of decompression sickness",
      "Better tolerance to narcosis",
      "Increased resistance to cold",
      "No known link to diving",
    ],
    correct: 0,
    explanation: "A PFO can let venous micro-bubbles pass directly to the arterial side without being filtered by the lungs, which is associated with an increased risk of certain types of DCS.",
  },
  {
    id: "phz-13", cat: "physiologie",
    q: "Seasickness in a student before a boat dive should be taken into account because:",
    choices: [
      "It can promote vomiting and dehydration, and increase stress before entering the water",
      "It has no impact on dive safety",
      "It always disappears instantly once underwater",
      "It only concerns the boat captain",
    ],
    correct: 0,
    explanation: "A student who feels unwell before a dive is a risk factor that shouldn't be overlooked in the briefing and in assessing their fitness to dive that day.",
  },
  {
    id: "phz-14", cat: "physiologie",
    q: "Alcohol and dehydration, before or after a dive, are generally considered:",
    choices: [
      "Aggravating factors for decompression sickness risk",
      "Having no effect at all on decompression risk",
      "Factors that reduce DCS risk",
      "Helpful for warming up after a dive",
    ],
    correct: 0,
    explanation: "Good hydration and avoiding alcohol around dives are commonly taught prevention tips, since alcohol promotes dehydration and alters risk perception.",
  },

  // ---------------- EQUIPMENT ----------------
  {
    id: "mat-01", cat: "materiel",
    q: "What is the role of a regulator's first stage?",
    choices: [
      "Deliver air on demand, at ambient pressure",
      "Reduce the tank's high pressure to a stable intermediate pressure",
      "Automatically inflate the BCD",
      "Measure the remaining pressure in the tank",
    ],
    correct: 1,
    explanation: "The 1st stage reduces the tank's HP (~200 bar) to an intermediate pressure (~8-10 bar above ambient); it's the 2nd stage that delivers air on demand.",
  },
  {
    id: "mat-02", cat: "materiel",
    q: "The submersible pressure gauge (SPG) is used to:",
    choices: [
      "Show depth",
      "Show the remaining pressure in the tank",
      "Show dive time",
      "Show water temperature",
    ],
    correct: 1,
    explanation: "The SPG is connected to the 1st stage's HP port and displays the pressure remaining in the tank.",
  },
  {
    id: "mat-03", cat: "materiel",
    q: "Why does a neoprene wetsuit lose buoyancy and insulation with depth?",
    choices: [
      "Neoprene shrinks from the cold",
      "Gas bubbles trapped in the neoprene compress under pressure (Boyle's Law)",
      "Water systematically seeps into the fabric",
      "Neoprene becomes chemically heavier",
    ],
    correct: 1,
    explanation: "Neoprene contains tiny gas bubbles that compress at depth, reducing both its insulating thickness and the buoyancy it provides.",
  },
  {
    id: "mat-04", cat: "materiel",
    q: "A buoyancy control device (BCD) is mainly used to:",
    choices: [
      "Supply emergency air in case of failure",
      "Adjust buoyancy by adding or releasing air",
      "Regulate body temperature",
      "Replace weighting",
    ],
    correct: 1,
    explanation: "The BCD compensates for buoyancy changes related to depth, tank consumption, etc.",
  },
  {
    id: "mat-05", cat: "materiel",
    q: "A dive computer continuously calculates:",
    choices: [
      "Only depth",
      "The remaining pressure in the tank",
      "The theoretical residual nitrogen in modeled tissues, based on the depth/time profile",
      "Only water temperature",
    ],
    correct: 2,
    explanation: "It applies a decompression model (an algorithm specific to the manufacturer) to the actual dive profile to estimate nitrogen loading and any required stops.",
  },
  {
    id: "mat-06", cat: "materiel",
    q: "The backup regulator (often called an \"octopus\") is used to:",
    choices: [
      "Supply air to a buddy in an out-of-air emergency, via an extra 2nd stage",
      "Inflate the BCD faster",
      "Replace the pressure gauge if it fails",
      "Measure depth",
    ],
    correct: 0,
    explanation: "This is a key piece of safety equipment in air-sharing procedures, usually marked in a bright color (often yellow) so a distressed buddy can spot it quickly.",
  },
  {
    id: "mat-07", cat: "materiel",
    q: "Weights worn by a diver should always be:",
    choices: [
      "Permanently fixed and impossible to drop",
      "Quickly releasable in an emergency",
      "Distributed only on the head",
      "As heavy as possible, regardless of actual buoyancy",
    ],
    correct: 1,
    explanation: "Weighting must always be quickly releasable in the event of a serious buoyancy problem — a fundamental safety point to check before every student dive.",
  },
  {
    id: "mat-08", cat: "materiel",
    q: "A key difference between a wetsuit and a drysuit is:",
    choices: [
      "A drysuit keeps the body isolated from water, while a wetsuit lets in a thin water film that warms against the body",
      "They work in exactly the same way",
      "A wetsuit is always warmer than a drysuit",
      "A drysuit can never be used in cold water",
    ],
    correct: 0,
    explanation: "The choice between the two mainly depends on water temperature and dive duration — a classic teaching point about equipment suited to the environment.",
  },
  {
    id: "mat-09", cat: "materiel",
    q: "After a dive, recommended basic equipment care consists of:",
    choices: [
      "Rinsing it with fresh water, especially the regulator (purge button not pressed) and the BCD",
      "Letting it dry directly with salt water still on it",
      "Only rinsing the exposure suit",
      "Storing wet gear in a closed bag without rinsing it",
    ],
    correct: 0,
    explanation: "Systematic fresh-water rinsing extends equipment life and is a good practice to pass on from the very first courses.",
  },
  {
    id: "mat-10", cat: "materiel",
    q: "A steel cylinder, compared to an aluminum cylinder of similar capacity, is generally:",
    choices: [
      "Denser and often more negatively buoyant, even nearly empty",
      "Always lighter when dry",
      "Built with a different valve that prevents use with any standard regulator",
      "Banned for recreational diving",
    ],
    correct: 0,
    explanation: "These buoyancy differences depending on cylinder material affect the weighting to plan for — an important point to properly advise your students.",
  },

  // ---------------- PLANNING & TABLES ----------------
  {
    id: "pla-01", cat: "planification",
    q: "What is \"residual nitrogen\" after a dive?",
    choices: [
      "The nitrogen still present in a diver's tissues after surfacing, as long as it hasn't been fully eliminated",
      "The nitrogen left in the dive tank",
      "Nitrogen produced by physical exertion",
      "An outdated term no longer in use",
    ],
    correct: 0,
    explanation: "This is the basis for calculating repetitive dives: the shorter the surface interval, the more residual nitrogen from the previous dive remains at the start of the next one.",
  },
  {
    id: "pla-02", cat: "planification",
    q: "Why follow a controlled ascent rate and never ascend too fast?",
    choices: [
      "Only to save air",
      "To give dissolved nitrogen time to gradually return to a gaseous phase and be eliminated without forming dangerous bubbles",
      "To avoid the cold",
      "It's just a comfort recommendation, unrelated to safety",
    ],
    correct: 1,
    explanation: "This is the central principle of decompression sickness prevention. The exact recommended rate depends on the standard/computer used: refer to the value in your SSI materials.",
  },
  {
    id: "pla-03", cat: "planification",
    q: "A safety stop on a no-decompression dive is used to:",
    choices: [
      "Replace ear equalization",
      "Add a safety margin by allowing extra time for off-gassing before reaching the surface",
      "Recharge the tank with air",
      "Warm up before exiting the water",
    ],
    correct: 1,
    explanation: "Widely recommended by training agencies (often a few minutes at shallow depth) as an extra safety margin — check the exact duration/depth recommended by SSI.",
  },
  {
    id: "pla-04", cat: "planification",
    q: "Why does altitude diving require adapted procedures?",
    choices: [
      "The water there is always colder",
      "The reference atmospheric pressure at the surface is lower than at sea level, which changes off-gassing calculations",
      "There's no difference, the same tables apply everywhere",
      "The air's oxygen is more concentrated there",
    ],
    correct: 1,
    explanation: "A lower surface pressure changes the pressure ratio between depth and surface: tables/computers must be adapted or set to altitude mode.",
  },
  {
    id: "pla-05", cat: "planification",
    q: "A longer surface interval between two dives allows:",
    choices: [
      "Increasing residual nitrogen before the 2nd dive",
      "Further reducing residual nitrogen before the 2nd dive, leaving more margin",
      "No longer needing a safety stop",
      "Has no effect on planning",
    ],
    correct: 1,
    explanation: "The longer the surface interval, the more nitrogen the body eliminates, which restores margin for the next dive (generally more no-stop time).",
  },
  {
    id: "pla-06", cat: "planification",
    q: "In case of a total air failure at shallow depth, the preferred emergency ascent procedure is generally:",
    choices: [
      "A controlled ascent, ideally assisted by the buddy, exhaling continuously so as not to hold the breath",
      "A full breath-hold straight to the surface, lungs blocked",
      "Descending to look for air elsewhere",
      "Waiting motionless, hoping the air comes back",
    ],
    correct: 0,
    explanation: "The core principle remains: never hold your breath while ascending, to avoid pulmonary barotrauma, while ascending as calmly as possible.",
  },
  {
    id: "pla-07", cat: "planification",
    q: "What can a dive computer do if a diver severely exceeds the limits it calculates?",
    choices: [
      "Nothing at all, in every case",
      "Lock out temporarily on some models, preventing dive data from being displayed for a set period",
      "Reset automatically with no consequence",
      "Automatically extend air endurance",
    ],
    correct: 1,
    explanation: "The exact behavior depends entirely on the model and manufacturer: some computers lock out after a severe violation. Always check the documentation for the model your students use.",
  },
  {
    id: "pla-08", cat: "planification",
    q: "So-called \"multilevel\" diving consists of:",
    choices: [
      "Descending straight to maximum depth and staying there for the whole dive",
      "Following a dive profile that gradually ascends through depth stages over time, which can extend no-stop time",
      "Only performing mandatory decompression stops",
      "A technique reserved for altitude diving",
    ],
    correct: 1,
    explanation: "By gradually ascending throughout the dive rather than staying at a constant depth, nitrogen buildup is limited — a principle a dive computer handles natively, unlike a classic square-profile table.",
  },
  {
    id: "pla-09", cat: "planification",
    q: "Why do many dive computers include an adjustable conservatism margin?",
    choices: [
      "To add extra safety given individual variability (fatigue, cold, age, physical condition...)",
      "Only to make the device harder to use",
      "Because the law requires it in every country",
      "It doesn't exist on any computer on the market",
    ],
    correct: 0,
    explanation: "Decompression risk isn't purely mathematical: individual factors influence susceptibility to accidents, which is why it's worth explaining this setting to students.",
  },
  {
    id: "pla-10", cat: "planification",
    q: "On a repetitive dive, if a long enough surface interval isn't respected, the main risk is:",
    choices: [
      "Starting the 2nd dive with higher residual nitrogen than expected, reducing the safety margin",
      "Only consuming more air",
      "No longer being able to use your computer",
      "No particular risk",
    ],
    correct: 0,
    explanation: "This is why managing the surface interval is a key point taught from the Open Water level onward and deepened in leadership training.",
  },

  // ---------------- ENVIRONMENT & SAFETY ----------------
  {
    id: "env-01", cat: "environnement",
    q: "Facing an unexpected strong current during a supervised dive, the instructor's priority is to:",
    choices: [
      "Continue the planned program unchanged",
      "Group the students together, maintain visual contact, and adapt/shorten the dive if needed for group safety",
      "Let each student make their own way to the surface",
      "Speed up the dive to finish faster",
    ],
    correct: 1,
    explanation: "Group management and real-time adaptation of the plan are at the heart of the skills assessed during the ITC/IE.",
  },
  {
    id: "env-02", cat: "environnement",
    q: "For night diving, an essential safety point to teach is:",
    choices: [
      "A backup light isn't necessary",
      "Plan for a primary light AND a backup light, and define clear light signals before entering the water",
      "Dive deeper than during the day",
      "Skip all signals, visibility doesn't matter",
    ],
    correct: 1,
    explanation: "Preparation (backup equipment, agreed light signals) is a classic teaching point in night dive briefings.",
  },
  {
    id: "env-03", cat: "environnement",
    q: "A thermocline refers to:",
    choices: [
      "A zone of sudden temperature change in the water column",
      "A surface current only",
      "A depth-measuring instrument",
      "A salinity variation only",
    ],
    correct: 0,
    explanation: "Useful to explain to students so they can anticipate the thermal discomfort and visual blur sometimes associated with crossing a thermocline.",
  },
  {
    id: "env-04", cat: "environnement",
    q: "Before a boat outing, a complete safety briefing for students should notably cover:",
    choices: [
      "Only the departure time",
      "Water entry/ladder exit procedures, recall signals, and what to do if separated from the group",
      "The planned meal menu",
      "Nothing specific, the standard briefing is always enough",
    ],
    correct: 1,
    explanation: "A structured, complete briefing adapted to the site and the day's conditions is a key teaching skill assessed for an instructor.",
  },
  {
    id: "env-05", cat: "environnement",
    q: "Drift diving is characterized by:",
    choices: [
      "A dive carried along by the current, with matching boat support",
      "A total ban on using a boat",
      "A dive always done at anchor, with no current at all",
      "A technique reserved only for deep technical diving",
    ],
    correct: 0,
    explanation: "It requires a specific briefing (end-of-dive signal, the boat tracking the group, possibly carrying a DSMB) that the instructor must be able to explain clearly.",
  },
  {
    id: "env-06", cat: "environnement",
    q: "Regarding marine life, the general good practice to teach students is:",
    choices: [
      "Touch and handle organisms to observe them better",
      "Observe without touching or feeding, keeping a respectful distance",
      "Collect samples on every dive",
      "Completely ignore the environment, it's not a teaching topic",
    ],
    correct: 1,
    explanation: "Environmental awareness (don't touch, don't feed, don't damage the seabed) is now an integral part of modern dive teaching, from the very first levels.",
  },
  {
    id: "env-07", cat: "environnement",
    q: "A DSMB (delayed surface marker buoy) is mainly used to:",
    choices: [
      "Signal the diver's position at the surface, especially in drift diving or when there's a current",
      "Replace the BCD",
      "Only act as a float to carry equipment",
      "Indicate the depth reached",
    ],
    correct: 0,
    explanation: "Knowing how to use and teach it properly (deploying it at the end of a dive or during a stop) is a valued safety skill in many leadership curricula.",
  },
  {
    id: "env-08", cat: "environnement",
    q: "In very cold water, an extra point of vigilance for the instructor is:",
    choices: [
      "The risk of a regulator free-flowing/freezing open, in addition to the risk of hypothermia",
      "No particular extra risk compared to temperate water",
      "Equipment needs no adaptation at all",
      "A total ban on diving below 15°C",
    ],
    correct: 0,
    explanation: "Some standard regulators are more prone to icing in very cold water, which is worth knowing before leading dives in this kind of environment.",
  },
  {
    id: "env-09", cat: "environnement",
    q: "A safety briefing before a quarry or lake dive (compared to the sea) should notably mention:",
    choices: [
      "Often reduced visibility, no current/tide but sometimes colder water at depth, and the site's regulated areas",
      "Nothing specific, the briefing is strictly identical to a sea dive",
      "Only the day's weather",
      "That fresh-water diving never needs a safety stop",
    ],
    correct: 0,
    explanation: "Each environment has its own specifics (visibility, marked thermoclines, no current but sometimes deceptive depth) to include in a site-adapted briefing.",
  },

  // ---------------- SSI: PATHWAY & TEACHING ----------------
  {
    id: "ssi-01", cat: "ssi",
    q: "According to the official SSI website (divessi.com), which step generally follows Divemaster / Dive Control Specialist in the pro pathway?",
    choices: [
      "Try Scuba",
      "The Instructor Training Course (ITC)",
      "Advanced Adventurer",
      "Specialty Diver",
    ],
    correct: 1,
    explanation: "According to divessi.com, the ITC is the next step after the Divemaster/Dive Control Specialist level, before the Instructor Evaluation (IE).",
  },
  {
    id: "ssi-02", cat: "ssi",
    q: "What must a candidate complete after the ITC to officially become an SSI Open Water Instructor?",
    choices: [
      "Nothing, certification is automatic at the end of the ITC",
      "Pass the Instructor Evaluation (IE)",
      "Wait 2 years of experience as a Dive Guide",
      "Go straight to Instructor Trainer",
    ],
    correct: 1,
    explanation: "SSI describes a 2-step approach: ITC then IE (Instructor Evaluation), after which the candidate becomes an Open Water Instructor.",
  },
  {
    id: "ssi-03", cat: "ssi",
    q: "The Dive Control Specialist (Dive Con) level at SSI broadly corresponds to:",
    choices: [
      "A beginner recreational diver level",
      "The first leadership level, combining Divemaster and Assistant Instructor skills",
      "The highest level, above Instructor Trainer",
      "A technical diving specialty only",
    ],
    correct: 1,
    explanation: "According to divessi.com, Dive Control Specialist is the first level of SSI's leadership system, including Divemaster and Assistant Instructor skills.",
  },
  {
    id: "ssi-04", cat: "ssi",
    q: "An SSI Instructor Trainer is qualified to:",
    choices: [
      "Only teach Open Water Diver",
      "Train and run Instructor Training Courses (ITC) as well as Instructor Crossovers",
      "Only dive for exploration, without leading groups",
      "Only deliver specialty courses",
    ],
    correct: 1,
    explanation: "According to SSI, the Instructor Trainer runs ITCs and Instructor Crossovers, in addition to being able to teach the full range of courses.",
  },
  {
    id: "ssi-05", cat: "ssi",
    q: "During the ITC, future instructors notably train to teach which programs (according to divessi.com)?",
    choices: [
      "Only cave diving",
      "Open Water Diver and specialties like Enriched Air Nitrox, Diver Stress & Rescue, or Perfect Buoyancy",
      "Only courses for children",
      "No specific program is mentioned",
    ],
    correct: 1,
    explanation: "According to SSI's official ITC description: academic sessions, confined water supervision, and training to teach Open Water Diver and specialties (Nitrox, Stress & Rescue, Perfect Buoyancy...).",
  },
  {
    id: "ssi-06", cat: "ssi",
    q: "As a future SSI instructor, which statement about staff-to-student ratios is correct?",
    choices: [
      "They're universal and never mentioned in the standards",
      "They're set by current SSI standards and must be checked in the official manual/MySSI, since they can vary by course and environment",
      "An instructor can always supervise an unlimited number of students",
      "Ratios only exist for technical diving",
    ],
    correct: 1,
    explanation: "This app deliberately doesn't give an exact ratio figure: these values belong to current SSI standards and must be checked in your up-to-date official materials.",
  },
  {
    id: "ssi-07", cat: "ssi",
    q: "Broadly speaking, what is the central role of an instructor during the Instructor Evaluation (IE)?",
    choices: [
      "Demonstrating only their own diving skills",
      "Demonstrating their ability to teach, lead a group, and manage safety — not just their personal diving level",
      "Doing the deepest possible dive",
      "Breaking an underwater time record",
    ],
    correct: 1,
    explanation: "An instructor's evaluation covers teaching, group management, and safety — well beyond personal diving skill alone.",
  },
  {
    id: "ssi-08", cat: "ssi",
    q: "In dive teaching, the classic sequence \"explain → demonstrate → guided practice → correct\" is used to:",
    choices: [
      "Structure the learning of a technical skill by giving the student a clear model before they practice",
      "Completely replace academic theory",
      "Only be used in a pool, never in open water",
      "Avoid having to correct students",
    ],
    correct: 0,
    explanation: "This is a general motor-learning principle used in dive teaching (and many technical disciplines), well beyond any single training agency.",
  },
  {
    id: "ssi-09", cat: "ssi",
    q: "Why is a structured debrief after each session with students recommended?",
    choices: [
      "To review what went well, what needs more work, and set clear goals for next time",
      "Only to fulfill an administrative formality",
      "Because it replaces ongoing skills assessment",
      "It's only useful at the very end of a full course, never after a single session",
    ],
    correct: 0,
    explanation: "Debriefing is an integral part of the teaching cycle: it reinforces learning and allows the program to be adjusted for each student.",
  },
  {
    id: "ssi-10", cat: "ssi",
    q: "Adapting your teaching to each student's pace and level (differentiation) matters because:",
    choices: [
      "Students progress at different speeds, and the same exercise can be too easy for one and too hard for another",
      "All students always learn in exactly the same way",
      "It's a waste of time for the instructor",
      "It only applies to theory teaching, never to practice",
    ],
    correct: 0,
    explanation: "A good instructor observes, adjusts pace, and personalizes feedback rather than running an identical script for every student.",
  },
  {
    id: "ssi-11", cat: "ssi",
    q: "Before entering the water, a mutual buddy check helps in particular to:",
    choices: [
      "Spot oversights or issues (air turned off, a loose strap, etc.) before they cause a problem underwater",
      "Replace the dive briefing",
      "Only be useful for beginner divers, never for instructors",
      "Only check everyone's watch time",
    ],
    correct: 0,
    explanation: "This is a safety practice widely taught across training agencies; the exact details (checklist, order of checks) can vary by program.",
  },
  {
    id: "ssi-12", cat: "ssi",
    q: "During a supervised course, an instructor must constantly:",
    choices: [
      "Keep an overall view of the group (headcount, position, each student's state), not just focus on one student at a time",
      "Focus only on the student having the most difficulty, ignoring the others",
      "Let students be fully independent from the very first lesson",
      "Stay at the surface for the entire supervised dive",
    ],
    correct: 0,
    explanation: "Overall group supervision (awareness) is a core skill assessed during instructor training, well beyond simply executing exercises technically.",
  },
  {
    id: "ssi-13", cat: "ssi",
    q: "According to the official SSI training portal, the pathway to Open Water Instructor comes down to 3 main steps. Which ones?",
    choices: [
      "AI (Assistant Instructor) → ITC (Instructor Training Course) → IE (Instructor Evaluation)",
      "Open Water Diver → Advanced → Rescue",
      "Try Scuba → Specialty Diver → Master Diver",
      "Dive Guide → Science of Diving → Nitrox",
    ],
    correct: 0,
    explanation: "This structure is confirmed both by the official training.divessi.com portal and by several official SSI PRO Instructor Training Center partners: AI, then ITC, then IE.",
  },
  {
    id: "ssi-14", cat: "ssi",
    q: "Among the prerequisites generally required to enroll in an SSI Instructor Training Course (ITC), you'll find:",
    choices: [
      "Being certified as a Divemaster (or equivalent), a minimum number of logged dives, and a Nitrox certification",
      "Never having dived before",
      "Only holding an Open Water Diver certification, with no other experience",
      "Having a university degree in marine biology",
    ],
    correct: 0,
    explanation: "According to the official SSI portal: Divemaster certification (or equivalent), at least 100 logged dives totaling 65 hours or more, and a Nitrox (Enriched Air) certification — plus a medical statement and a current first aid certificate. Exact values should be reconfirmed with your training center, as an Instructor Trainer may clarify details depending on context.",
  },
  {
    id: "ssi-15", cat: "ssi",
    q: "The medical statement (physician's approval to dive) required for the ITC generally must be dated:",
    choices: [
      "Less than one year old",
      "There's no validity limit at all",
      "Less than 10 years old",
      "The same day as the exam only",
    ],
    correct: 0,
    explanation: "According to the official SSI portal, a physician's approval to dive less than one year old is generally required for the ITC — reconfirm with your training center.",
  },
  {
    id: "ssi-16", cat: "ssi",
    q: "The first aid / CPR / oxygen administration certificate (e.g. SSI React Right) required for the ITC generally must have been obtained:",
    choices: [
      "Within the last 24 months",
      "More than 10 years ago, with no limit",
      "On the day of enrollment only",
      "This certification is never required",
    ],
    correct: 0,
    explanation: "The official SSI portal mentions a 24-month validity for the first aid/CPR/oxygen certificate required to enter the ITC — independently confirmed by several official SSI PRO Instructor Training Center partners.",
  },
  {
    id: "ssi-17", cat: "ssi",
    q: "The ITC includes numbered \"Academic Sessions\" (roughly 1 to 10). Which of these titles is genuinely one of them?",
    choices: [
      "\"Overview of SSI\"",
      "\"Introduction to Cave Diving History\"",
      "\"19th-Century Dive Equipment History\"",
      "\"Diver Cooking and Nutrition\"",
    ],
    correct: 0,
    explanation: "Confirmed by the official SSI portal: the ITC's Academic Sessions notably include \"Overview of SSI,\" \"Duties of an SSI Professional,\" \"Program Administration,\" \"The Open Water Diver Program,\" \"Diver Stress & Rescue and Divemaster,\" and \"The Business of Diving,\" among others.",
  },
  {
    id: "ssi-18", cat: "ssi",
    q: "During the ITC, \"Practical Application Sessions\" (workshops) are mainly used to:",
    choices: [
      "Practice actually teaching course segments (e.g. Open Water Diver, Nitrox, Diver Stress & Rescue) under supervision, with feedback and video analysis",
      "Only take a final written exam",
      "Do recreational diving with no teaching objective",
      "Fully replace the theoretical academic sessions",
    ],
    correct: 0,
    explanation: "These workshops, often followed by video analysis and a debrief, let instructor candidates practice teaching real course segments before doing it alone with real students.",
  },
];

export const MEMO_CARDS = [
  {
    id: "m-physique",
    cat: "physique",
    title: "Physics — the 3 laws to know by heart",
    bullets: [
      "Boyle's Law: P1·V1 = P2·V2 (constant temperature) → basis of buoyancy, air consumption, barotrauma.",
      "Dalton: Ptotal = sum of partial pressures → basis of nitrox MOD calculation.",
      "Henry: dissolved gas amount ∝ partial pressure → basis of all decompression theory.",
      "Rule of thumb: ≈ +1 bar / 10 m of seawater, on top of the surface atmospheric bar (confirm with your course materials).",
      "Archimedes: upward force = weight of displaced fluid → basis of buoyancy.",
      "Underwater: objects ~25%/33% closer/larger (refraction), red absorbed first, sound ~4x faster than in air, heat lost much faster than in air.",
    ],
  },
  {
    id: "m-physiologie",
    cat: "physiologie",
    title: "Physiology — accidents to know",
    bullets: [
      "Nitrogen narcosis: linked to nitrogen partial pressure at depth, very individual sensitivity.",
      "Decompression sickness (DCS): too-fast ascent → nitrogen bubbles in tissues/blood.",
      "Pulmonary barotrauma: blocked breathing on ascent → risk of gas embolism, potentially fatal.",
      "O2 toxicity: risk at high partial pressure (nitrox/tech) → always calculate MOD.",
      "Barotrauma: ears/sinuses (descent), mask (descent), lungs (ascent) — never force an equalization.",
      "Equalization techniques: Valsalva, Frenzel — gentler variants worth knowing to help a struggling student.",
      "DCS aggravating factors: alcohol, dehydration, patent foramen ovale (PFO), fatigue, cold.",
      "Hyperventilation before breath-holding: dangerous, can cause a hypoxic blackout with no warning sign.",
    ],
  },
  {
    id: "m-materiel",
    cat: "materiel",
    title: "Equipment — key functions",
    bullets: [
      "1st stage: reduces tank HP to a stable intermediate pressure.",
      "2nd stage: delivers air on demand, at ambient pressure.",
      "SPG (pressure gauge): remaining pressure in the tank.",
      "BCD: adjusts buoyancy (adding/releasing air).",
      "Neoprene: compresses with depth → loss of buoyancy and thermal insulation.",
      "Dive computer: models tissue nitrogen loading from the actual dive profile.",
      "Octopus (2nd regulator): emergency air for a buddy who is out of air.",
      "Weights: always quickly releasable in an emergency.",
      "Steel vs aluminum cylinder: different end-of-dive buoyancy (aluminum tends to go positive when empty) → adjust weighting accordingly.",
    ],
  },
  {
    id: "m-planification",
    cat: "planification",
    title: "Planning — key concepts",
    bullets: [
      "Residual nitrogen: nitrogen still present in the body after a dive, as long as it hasn't been fully eliminated.",
      "Longer surface interval → more nitrogen eliminated → more margin for the next dive.",
      "Controlled ascent rate: essential to let nitrogen return to a gaseous phase gently.",
      "Safety stop: extra safety margin at the end of a no-decompression dive.",
      "Altitude diving: lower surface pressure → adapted procedures/tables needed.",
      "Multilevel diving: gradually ascending during the dive limits nitrogen buildup compared to a \"square\" profile.",
      "Adjustable computer conservatism: extra safety against individual variability (cold, age, fatigue...).",
      "⚠️ Precise values (durations, depths, rates, ratios) must be checked in your current official SSI materials (manual, MySSI, your Instructor Trainer) — deliberately not reproduced here.",
    ],
  },
  {
    id: "m-environnement",
    cat: "environnement",
    title: "Environment & safety — leadership reflexes",
    bullets: [
      "Strong current: group the students, maintain visual contact, adapt or shorten the dive if needed.",
      "Night diving: primary + backup lighting, light signals defined before entering the water.",
      "Thermocline: prepare students for the thermal discomfort and visual blur.",
      "Boat briefing: entry/exit procedures, recall signals, what to do if separated.",
      "Managing a breathless student: stabilize, visual/physical contact, slow breathing, stop the exertion.",
      "DSMB: signals surface position, useful in drift diving or with a current.",
      "Marine life: observe without touching or feeding.",
      "Cold water: risk of regulator free-flow/icing, in addition to hypothermia.",
    ],
  },
  {
    id: "m-pedagogie",
    cat: "ssi",
    title: "Teaching & leadership — general principles",
    bullets: [
      "Skill-learning sequence: explain → demonstrate → guided practice → correct.",
      "Debrief after every session: what worked, what needs more work, goals going forward.",
      "Differentiation: adapt pace and exercises to each student's actual level, not one script for everyone.",
      "Buddy check before entering the water: spot oversights/issues beforehand.",
      "Group supervision (awareness): keep an overall view, not just focus on one student at a time.",
      "⚠️ These are general teaching principles; your agency's precise procedures/checklists may have their own additional formalization worth knowing.",
    ],
  },
  {
    id: "m-ssi",
    cat: "ssi",
    title: "SSI pathway — reference points (source: official training.divessi.com portal + partner centers)",
    bullets: [
      "Recreational → pro: Open Water Diver → Advanced Adventurer/specialties → Dive Guide / Science of Diving → Divemaster.",
      "Toward instructing, 3 steps: AI (Assistant Instructor) → ITC (Instructor Training Course) → IE (Instructor Evaluation) → SSI Open Water Instructor.",
      "Common ITC prerequisites (reconfirm with your center): certified Divemaster, ~100 logged dives (65h+), Nitrox certification, medical statement less than 1 year old, first aid/CPR/O2 certificate less than 24 months old.",
      "ITC Academic Sessions (10 numbered sessions): Overview of SSI, Duties of an SSI Professional, Program Administration, Academic Sessions, In-Water Teaching, Assistant Instructor Programs, The Open Water Diver Program, Open Water Instructor Specialties, Diver Stress & Rescue and Divemaster, The Business of Diving.",
      "Practical Application Sessions: workshops where the candidate actually teaches course segments (OWD, Nitrox, Stress & Rescue...) under supervision, with video analysis and debrief.",
      "An Open Water Instructor can then move on to Specialty Instructor, then Instructor Trainer (qualified to run ITCs and Instructor Crossovers).",
      "⚠️ Structure and prerequisites confirmed on the official SSI portal and cross-checked with several SSI PRO partner centers (2026) — standards evolve and an Instructor Trainer may clarify details: always reconfirm with your center.",
    ],
  },
  {
    id: "m-disclaimer",
    cat: "ssi",
    title: "⚠️ Read before you study",
    bullets: [
      "This app is a PERSONAL revision tool, built independently. It is not edited, verified, or officially approved by SSI (Scuba Schools International).",
      "Physics/physiology/equipment questions reflect general knowledge common to all diving agencies.",
      "For any precise figures (ratios, exam procedures, tables, standards), ALWAYS refer to your SSI Instructor Manual, MySSI, and your Instructor Trainer — these are the only sources that count.",
      "If in doubt about a safety point, never rely on this app alone.",
    ],
  },
  {
    id: "m-sources",
    cat: "ssi",
    title: "🔎 How this content was verified",
    bullets: [
      "Every physics/physiology/safety fact was cross-checked against at least 2 independent, recognized sources: DAN (Divers Alert Network), Merck Manual, NCBI/PubMed, or official diving agency websites.",
      "The SSI pathway structure was verified on the official divessi.com site and cross-checked with other independent SSI training centers.",
      "The full list of sources and links used is in the SOURCES.md file of the project repository.",
      "This verification greatly reduces the risk of factual error but has not been reviewed by a dive medicine professional or an SSI Instructor Trainer — it is not an absolute guarantee.",
    ],
  },
];
