// Contenu de révision — Instructor Prep
//
// IMPORTANT : ce contenu couvre des connaissances générales de plongée
// (physique, physiologie, matériel) communes à tous les organismes de
// formation, ainsi que la structure publique du cursus SSI telle que
// publiée sur divessi.com. Il NE remplace PAS le SSI Instructor Manual,
// le MySSI, ni les indications de ton Instructor Trainer. Les valeurs
// chiffrées précises (ratios encadrant/élèves, procédures d'examen,
// tables RDP/eRDPml) doivent être vérifiées auprès de tes supports
// officiels SSI en vigueur : elles évoluent et ne sont pas reproduites
// ici quand elles sont spécifiques à SSI ou sujettes à changement.

export const CATEGORIES = [
  { id: "physique", label: "Physique", icon: "🌊", color: "#1d6fa5" },
  { id: "physiologie", label: "Physiologie & accidents", icon: "🫁", color: "#c62828" },
  { id: "materiel", label: "Matériel", icon: "🤿", color: "#2e7d32" },
  { id: "planification", label: "Planification & tables", icon: "🧭", color: "#6a4fb6" },
  { id: "environnement", label: "Environnement & sécurité", icon: "🌐", color: "#00838f" },
  { id: "ssi", label: "Parcours & pédagogie SSI", icon: "🎓", color: "#ef6c00" },
];

export const QUESTIONS = [
  // ---------------- PHYSIQUE ----------------
  {
    id: "phy-01", cat: "physique",
    q: "Que dit la loi de Boyle-Mariotte, essentielle pour comprendre la plongée ?",
    choices: [
      "À température constante, le produit pression × volume d'un gaz reste constant (P1V1 = P2V2)",
      "La pression d'un mélange gazeux est la somme des pressions partielles de ses composants",
      "La quantité de gaz dissous dans un liquide est proportionnelle à sa pression partielle",
      "Le volume d'un gaz est proportionnel à sa température en degrés Celsius",
    ],
    correct: 0,
    explanation: "Boyle-Mariotte régit la compression/expansion des gaz avec la profondeur : c'est la base de la flottabilité, de la consommation d'air et des barotraumatismes.",
  },
  {
    id: "phy-02", cat: "physique",
    q: "La loi de Dalton permet d'expliquer directement :",
    choices: [
      "La flottabilité d'un corps immergé",
      "La pression partielle de chaque gaz dans un mélange respiré (ex. calcul de la MOD du nitrox)",
      "La vitesse de propagation du son sous l'eau",
      "La formation de buée dans le masque",
    ],
    correct: 1,
    explanation: "Dalton : la pression totale d'un mélange = somme des pressions partielles. Indispensable pour le calcul de la profondeur maximale d'utilisation (MOD) en nitrox.",
  },
  {
    id: "phy-03", cat: "physique",
    q: "La loi de Henry est à la base de quel phénomène en plongée ?",
    choices: [
      "La narcose à l'azote",
      "La dissolution des gaz dans les tissus et le sang, et donc la théorie de la décompression",
      "La réfraction de la lumière sous l'eau",
      "La perte de chaleur corporelle",
    ],
    correct: 1,
    explanation: "Henry : la quantité de gaz dissous dans un liquide est proportionnelle à la pression partielle de ce gaz — c'est le fondement de toute la théorie de décompression.",
  },
  {
    id: "phy-04", cat: "physique",
    q: "Un plongeur descend en eau de mer. Par rapport à l'eau douce, sa flottabilité est :",
    choices: [
      "Identique, la densité de l'eau ne change pas",
      "Plus négative (il coule davantage)",
      "Plus positive (l'eau salée est plus dense, environ 1,025 kg/L contre 1,000 kg/L)",
      "Imprévisible, cela dépend uniquement de la température",
    ],
    correct: 2,
    explanation: "L'eau salée étant plus dense, elle exerce une poussée d'Archimède plus forte : il faut généralement plus de lest en mer qu'en eau douce.",
  },
  {
    id: "phy-05", cat: "physique",
    q: "En eau de mer, la pression augmente approximativement de :",
    choices: [
      "1 bar tous les 10 mètres",
      "1 bar tous les 20 mètres",
      "0,5 bar tous les 10 mètres",
      "2 bars tous les 10 mètres",
    ],
    correct: 0,
    explanation: "Règle générale largement utilisée dans l'enseignement : environ +1 bar par 10 m d'eau de mer, en plus des 1 bar de pression atmosphérique en surface. Vérifie les valeurs exactes retenues par ton support de cours.",
  },
  {
    id: "phy-06", cat: "physique",
    q: "Pourquoi la consommation d'air (en volume à pression atmosphérique) augmente-t-elle avec la profondeur ?",
    choices: [
      "Le détendeur devient moins performant en profondeur",
      "Le plongeur respire plus vite par réflexe",
      "L'air est plus dense en profondeur : chaque respiration consomme plus de molécules de gaz pour un même volume pulmonaire",
      "L'eau froide réduit la capacité pulmonaire",
    ],
    correct: 2,
    explanation: "À pression plus élevée, l'air est plus dense : un même volume pulmonaire correspond à davantage de gaz prélevé dans le bloc, d'où une consommation accrue en litres/bar.",
  },
  {
    id: "phy-07", cat: "physique",
    q: "Que se passe-t-il pour un ballon de recherche (lift bag) qui remonte en surface sans contrôle ?",
    choices: [
      "Rien, sa flottabilité reste constante",
      "Il se dégonfle automatiquement",
      "L'air qu'il contient se dilate en remontant (Boyle-Mariotte), accélérant sa remontée de façon incontrôlée",
      "Il devient neutre en surface",
    ],
    correct: 2,
    explanation: "C'est un point pédagogique classique pour illustrer les dangers de Boyle-Mariotte en remontée non contrôlée, y compris pour la flottabilité du plongeur lui-même.",
  },

  {
    id: "phy-08", cat: "physique",
    q: "La loi d'Archimède, qui régit la flottabilité, énonce que :",
    choices: [
      "Tout corps plongé dans un fluide subit une poussée verticale vers le haut égale au poids du volume de fluide déplacé",
      "Le volume d'un gaz est inversement proportionnel à sa pression",
      "La pression d'un gaz augmente avec la température",
      "La densité de l'eau diminue avec la profondeur",
    ],
    correct: 0,
    explanation: "C'est le principe physique qui explique pourquoi un plongeur peut être en flottabilité positive, négative ou neutre selon son volume déplacé et son poids.",
  },
  {
    id: "phy-09", cat: "physique",
    q: "Sous l'eau, à travers un masque, les objets paraissent généralement :",
    choices: [
      "Plus petits et plus loin qu'en réalité",
      "Plus gros et plus proches qu'en réalité (effet de la réfraction)",
      "De la même taille et à la même distance qu'à l'air libre",
      "Toujours flous, sans effet de taille",
    ],
    correct: 1,
    explanation: "La réfraction de la lumière entre l'eau et l'air emprisonné dans le masque fait paraître les objets environ 25% plus proches et environ 33% plus gros — un point important à enseigner aux élèves pour l'estimation des distances.",
  },
  {
    id: "phy-10", cat: "physique",
    q: "En profondeur, quelle couleur du spectre disparaît en premier à l'œil nu (sans lumière artificielle) ?",
    choices: [
      "Le bleu",
      "Le vert",
      "Le rouge",
      "Le jaune",
    ],
    correct: 2,
    explanation: "L'eau absorbe progressivement les grandes longueurs d'onde : le rouge disparaît le premier (dès quelques mètres), puis l'orange, le jaune... le bleu/vert restent visibles le plus longtemps.",
  },
  {
    id: "phy-11", cat: "physique",
    q: "Le son se déplace sous l'eau :",
    choices: [
      "Beaucoup plus lentement que dans l'air",
      "À peu près à la même vitesse que dans l'air",
      "Beaucoup plus vite que dans l'air (environ 4 fois)",
      "Le son ne se propage pas du tout sous l'eau",
    ],
    correct: 2,
    explanation: "Cette vitesse accrue rend aussi la provenance d'un son beaucoup plus difficile à localiser sous l'eau qu'en surface — utile à savoir pour expliquer pourquoi on utilise des signaux visuels/tactiles plutôt que la voix.",
  },
  {
    id: "phy-12", cat: "physique",
    q: "Pourquoi un plongeur perd-il de la chaleur corporelle beaucoup plus vite dans l'eau que dans l'air à température égale ?",
    choices: [
      "L'eau conduit la chaleur bien plus efficacement que l'air (plusieurs dizaines de fois plus vite)",
      "L'eau contient toujours moins de chaleur que l'air",
      "Ce n'est pas vrai, la perte de chaleur est identique",
      "Uniquement à cause du vent apparent créé par les palmes",
    ],
    correct: 0,
    explanation: "La conductivité thermique de l'eau est très supérieure à celle de l'air, ce qui explique le besoin de protection thermique (combinaison) même dans une eau qui semble « tiède ».",
  },
  {
    id: "phy-13", cat: "physique",
    q: "Un bloc en acier plein et un bloc en aluminium plein de même volume : lequel a tendance à devenir le plus flottant en fin de plongée quand il se vide ?",
    choices: [
      "L'aluminium, qui devient plus vite positif en se vidant d'air",
      "L'acier, systématiquement",
      "Cela ne dépend jamais du matériau",
      "Les deux deviennent négatifs en se vidant",
    ],
    correct: 0,
    explanation: "Point pédagogique classique de gestion du lestage : les blocs alu ont tendance à devenir positifs en fin de plongée quand ils sont vides, contrairement à l'acier qui reste souvent plus négatif — à ajuster selon le modèle exact du bloc.",
  },

  // ---------------- PHYSIOLOGIE ----------------
  {
    id: "phz-01", cat: "physiologie",
    q: "La narcose à l'azote est principalement causée par :",
    choices: [
      "Une pression partielle élevée d'azote à profondeur",
      "Un manque d'oxygène",
      "Une accumulation de CO2 due à un effort physique",
      "Le froid ressenti en profondeur",
    ],
    correct: 0,
    explanation: "Souvent comparée à une ivresse, la narcose est liée à l'augmentation de la pression partielle d'azote. La sensibilité varie fortement d'un individu à l'autre — ne retiens pas un seuil unique comme absolu.",
  },
  {
    id: "phz-02", cat: "physiologie",
    q: "L'accident de décompression (ADD) résulte principalement de :",
    choices: [
      "Une remontée trop rapide provoquant la formation de bulles d'azote dans les tissus/le sang",
      "Une pression partielle d'oxygène trop faible",
      "Un excès de CO2 par hypoventilation",
      "Une déshydratation avant la plongée",
    ],
    correct: 0,
    explanation: "Une désaturation trop rapide empêche l'azote dissous de repasser en phase gazeuse progressivement, formant des bulles qui peuvent obstruer la circulation ou léser les tissus.",
  },
  {
    id: "phz-03", cat: "physiologie",
    q: "Quel est le risque principal d'une remontée rapide en apnée respiratoire bloquée (poumon plein) ?",
    choices: [
      "La narcose à l'azote",
      "La surpression pulmonaire, pouvant aller jusqu'à l'embolie gazeuse",
      "L'essoufflement",
      "L'hypothermie",
    ],
    correct: 1,
    explanation: "Si l'air ne peut pas s'échapper librement pendant la remontée, l'expansion du gaz dans les poumons (Boyle-Mariotte) peut provoquer une surpression pulmonaire, un accident grave et potentiellement mortel.",
  },
  {
    id: "phz-04", cat: "physiologie",
    q: "La toxicité de l'oxygène (effet SNC / convulsions) est associée à :",
    choices: [
      "Une pression partielle d'O2 trop faible",
      "Une pression partielle d'O2 élevée, typiquement au-delà des seuils utilisés en nitrox/tech",
      "Un excès d'azote uniquement",
      "Une eau trop froide",
    ],
    correct: 1,
    explanation: "C'est pourquoi les formations nitrox insistent sur le calcul de la MOD (profondeur max d'utilisation) pour rester sous un seuil de pression partielle d'O2 donné par les standards de ton organisme.",
  },
  {
    id: "phz-05", cat: "physiologie",
    q: "Un placage de masque (mask squeeze) est un exemple de :",
    choices: [
      "Barotraumatisme de descente",
      "Barotraumatisme de remontée",
      "Accident de décompression",
      "Narcose",
    ],
    correct: 0,
    explanation: "En descente, si l'air à l'intérieur du masque n'est pas rééquilibré, la pression externe croissante peut créer un effet ventouse sur le visage et les yeux.",
  },
  {
    id: "phz-06", cat: "physiologie",
    q: "Un plongeur ne parvient pas à équilibrer ses oreilles en descente et ressent une douleur. Quelle est la bonne conduite ?",
    choices: [
      "Continuer à descendre, la douleur va passer",
      "Forcer une manœuvre de Valsalva plus intense",
      "Remonter légèrement, retenter l'équilibrage en douceur, ne jamais forcer",
      "Retirer son masque pour égaliser plus facilement",
    ],
    correct: 2,
    explanation: "Principe pédagogique fondamental à transmettre aux élèves : ne jamais forcer une équilibration, remonter un peu si besoin, redescendre plus lentement.",
  },
  {
    id: "phz-07", cat: "physiologie",
    q: "L'essoufflement (dyspnée) en plongée est le plus souvent déclenché par :",
    choices: [
      "Un effort physique excessif et une accumulation de CO2",
      "Un froid excessif uniquement",
      "Une pression partielle d'azote élevée",
      "Une déshydratation",
    ],
    correct: 0,
    explanation: "L'effort couplé à une ventilation inadaptée entraîne une accumulation de CO2, créant une sensation d'étouffement qui peut s'auto-entretenir en panique si mal gérée.",
  },
  {
    id: "phz-08", cat: "physiologie",
    q: "En tant que futur instructeur, quelle est la priorité pédagogique face à un élève en début d'essoufflement ?",
    choices: [
      "Le faire remonter en panique le plus vite possible",
      "Le stabiliser, établir un contact visuel et physique, ralentir la respiration, arrêter l'effort avant d'envisager la suite",
      "L'ignorer, cela se résout tout seul",
      "Lui retirer son détendeur pour qu'il respire mieux",
    ],
    correct: 1,
    explanation: "La gestion du stress et de l'essoufflement d'un élève est un point central des modules de gestion de groupe/rescue de la formation instructeur.",
  },

  {
    id: "phz-09", cat: "physiologie",
    q: "Parmi ces techniques d'équilibrage des oreilles, laquelle est couramment enseignée en plongée (en plus de la Valsalva) ?",
    choices: [
      "La manœuvre de Frenzel",
      "La manœuvre de Heimlich",
      "La respiration abdominale forcée",
      "Le pincement du masque uniquement",
    ],
    correct: 0,
    explanation: "La technique de Frenzel (utilisation de la langue/glotte pour comprimer l'air vers les trompes d'Eustache) est une alternative à la Valsalva, souvent présentée comme plus douce pour les oreilles.",
  },
  {
    id: "phz-10", cat: "physiologie",
    q: "L'hyperventilation volontaire avant une descente en apnée est dangereuse car elle peut provoquer :",
    choices: [
      "Une syncope (perte de connaissance) par baisse du CO2 sans avertissement suffisant avant le manque d'oxygène",
      "Une accélération du rythme cardiaque bénéfique",
      "Une meilleure oxygénation sans aucun risque",
      "Un simple mal de tête sans gravité",
    ],
    correct: 0,
    explanation: "En abaissant artificiellement le CO2 (signal d'alerte respiratoire) sans augmenter significativement l'oxygène disponible, l'hyperventilation retarde l'envie de respirer et peut provoquer une syncope hypoxique sans signe avant-coureur.",
  },
  {
    id: "phz-11", cat: "physiologie",
    q: "Une intoxication au monoxyde de carbone (air contaminé, ex. compresseur mal positionné) peut provoquer :",
    choices: [
      "Maux de tête, confusion, nausées, pouvant aller jusqu'à la perte de connaissance",
      "Uniquement une légère toux sans autre symptôme",
      "Aucun symptôme détectable avant l'accident",
      "Une amélioration temporaire de la vigilance",
    ],
    correct: 0,
    explanation: "D'où l'importance, pour un futur instructeur, de connaître les bonnes pratiques de positionnement des compresseurs et les signes d'alerte à surveiller chez les élèves.",
  },
  {
    id: "phz-12", cat: "physiologie",
    q: "La présence d'un foramen ovale perméable (PFO) chez un plongeur est un facteur associé à :",
    choices: [
      "Un risque accru d'accident de décompression",
      "Une meilleure tolérance à la narcose",
      "Une résistance accrue au froid",
      "Aucun lien connu avec la plongée",
    ],
    correct: 0,
    explanation: "Un PFO peut permettre à des micro-bulles veineuses de passer directement côté artériel sans être filtrées par les poumons, ce qui est associé à un risque accru de certains types d'ADD.",
  },
  {
    id: "phz-13", cat: "physiologie",
    q: "Le mal de mer (mal des transports) chez un élève avant une plongée bateau doit être pris en compte car :",
    choices: [
      "Il peut favoriser les vomissements et la déshydratation, et augmenter le stress avant la mise à l'eau",
      "Il n'a aucun impact sur la sécurité de la plongée",
      "Il disparaît toujours instantanément une fois sous l'eau",
      "Il ne concerne que le capitaine du bateau",
    ],
    correct: 0,
    explanation: "Un élève mal en point avant la plongée est un facteur de risque à ne pas négliger dans le briefing et l'évaluation de son aptitude à plonger ce jour-là.",
  },
  {
    id: "phz-14", cat: "physiologie",
    q: "L'alcool et la déshydratation, avant ou après une plongée, sont généralement considérés comme :",
    choices: [
      "Des facteurs aggravants du risque d'accident de décompression",
      "Sans aucun effet sur le risque de décompression",
      "Des facteurs qui réduisent le risque d'ADD",
      "Utiles pour se réchauffer après la plongée",
    ],
    correct: 0,
    explanation: "Une bonne hydratation et l'évitement de l'alcool autour des plongées sont des conseils de prévention couramment enseignés, l'alcool favorisant la déshydratation et modifiant la perception du risque.",
  },

  // ---------------- MATERIEL ----------------
  {
    id: "mat-01", cat: "materiel",
    q: "Quel est le rôle du premier étage d'un détendeur ?",
    choices: [
      "Délivrer l'air à la demande, à la pression ambiante",
      "Réduire la haute pression du bloc à une pression intermédiaire stable",
      "Gonfler le gilet automatiquement",
      "Mesurer la pression restante dans le bloc",
    ],
    correct: 1,
    explanation: "Le 1er étage réduit la HP du bloc (~200 bars) à une pression intermédiaire (~8-10 bars au-dessus de l'ambiante) ; c'est le 2e étage qui délivre l'air à la demande.",
  },
  {
    id: "mat-02", cat: "materiel",
    q: "Le manomètre (SPG) sert à :",
    choices: [
      "Indiquer la profondeur",
      "Indiquer la pression restante dans le bloc",
      "Indiquer le temps de plongée",
      "Indiquer la température de l'eau",
    ],
    correct: 1,
    explanation: "Le SPG (submersible pressure gauge) est relié à la sortie HP du 1er étage et affiche la pression restante dans le bloc.",
  },
  {
    id: "mat-03", cat: "materiel",
    q: "Pourquoi une combinaison néoprène perd-elle en flottabilité et en isolation avec la profondeur ?",
    choices: [
      "Le néoprène se rétracte sous l'effet du froid",
      "Les bulles de gaz emprisonnées dans le néoprène se compriment avec la pression (Boyle-Mariotte)",
      "L'eau s'infiltre systématiquement dans le tissu",
      "Le néoprène devient plus lourd chimiquement",
    ],
    correct: 1,
    explanation: "Le néoprène contient des micro-bulles de gaz qui se compressent en profondeur, réduisant à la fois son épaisseur isolante et la flottabilité qu'il procure.",
  },
  {
    id: "mat-04", cat: "materiel",
    q: "Un gilet stabilisateur (BCD) permet principalement de :",
    choices: [
      "Fournir de l'air de secours en cas de panne",
      "Ajuster la flottabilité en ajoutant ou évacuant de l'air",
      "Réguler la température corporelle",
      "Remplacer le lestage",
    ],
    correct: 1,
    explanation: "Le BCD (Buoyancy Control Device) permet de compenser les variations de flottabilité liées à la profondeur, à l'usure du bloc, etc.",
  },
  {
    id: "mat-05", cat: "materiel",
    q: "Un ordinateur de plongée calcule en continu :",
    choices: [
      "Uniquement la profondeur",
      "La pression restante dans le bloc",
      "L'azote résiduel théorique dans les tissus modélisés, en fonction du profil profondeur/temps",
      "La température de l'eau uniquement",
    ],
    correct: 2,
    explanation: "Il applique un modèle de désaturation (algorithme propre au fabricant) au profil réel de la plongée pour estimer la charge en azote et les paliers éventuels.",
  },

  {
    id: "mat-06", cat: "materiel",
    q: "Le détendeur de secours (souvent appelé « octopus ») sert à :",
    choices: [
      "Fournir de l'air à un binôme en cas de panne d'air, via un 2e étage supplémentaire",
      "Gonfler le gilet plus rapidement",
      "Remplacer le manomètre en cas de panne",
      "Mesurer la profondeur",
    ],
    correct: 0,
    explanation: "C'est un équipement de sécurité central dans les procédures de partage d'air, généralement identifié par une couleur voyante (souvent jaune) pour être repéré rapidement par le binôme en détresse.",
  },
  {
    id: "mat-07", cat: "materiel",
    q: "Le lest (poids) porté par un plongeur doit toujours être :",
    choices: [
      "Fixé de façon permanente et impossible à larguer",
      "Rapidement largable en cas d'urgence",
      "Réparti uniquement sur la tête",
      "Le plus lourd possible, sans lien avec la flottabilité réelle",
    ],
    correct: 1,
    explanation: "Le lestage doit toujours pouvoir être largué rapidement en cas de problème de flottabilité grave — un point de sécurité fondamental à vérifier avant chaque plongée d'élèves.",
  },
  {
    id: "mat-08", cat: "materiel",
    q: "Une différence clé entre une combinaison humide et une combinaison étanche est :",
    choices: [
      "La combinaison étanche isole le corps de l'eau, la combinaison humide laisse entrer un film d'eau qui se réchauffe au contact du corps",
      "Elles sont strictement identiques dans leur fonctionnement",
      "La combinaison humide est toujours plus chaude que l'étanche",
      "La combinaison étanche ne peut jamais servir en eau froide",
    ],
    correct: 0,
    explanation: "Le choix entre les deux dépend notamment de la température de l'eau et de la durée de plongée — un point pédagogique classique du matériel adapté à l'environnement.",
  },
  {
    id: "mat-09", cat: "materiel",
    q: "Après une plongée, l'entretien de base du matériel recommandé consiste à :",
    choices: [
      "Le rincer à l'eau douce, en particulier le détendeur (bouton de purge non appuyé) et le gilet",
      "Le laisser sécher directement avec l'eau salée dessus",
      "Ne rincer que la combinaison",
      "Ranger le matériel humide dans un sac fermé sans le rincer",
    ],
    correct: 0,
    explanation: "Un rinçage systématique à l'eau douce prolonge la durée de vie du matériel et fait partie des bonnes pratiques à transmettre dès les premiers cours.",
  },
  {
    id: "mat-10", cat: "materiel",
    q: "Un cylindre (bloc) en acier, comparé à un cylindre en aluminium de contenance similaire, est généralement :",
    choices: [
      "Plus dense et souvent plus négatif, y compris quasi vide",
      "Toujours plus léger à sec",
      "Fabriqué avec un embout différent empêchant tout détendeur standard",
      "Interdit pour la plongée loisir",
    ],
    correct: 0,
    explanation: "Ces différences de flottabilité selon le matériau du bloc influencent le lestage à prévoir — un point à bien maîtriser pour conseiller correctement ses élèves.",
  },

  // ---------------- PLANIFICATION & TABLES ----------------
  {
    id: "pla-01", cat: "planification",
    q: "Qu'appelle-t-on l'azote résiduel après une plongée ?",
    choices: [
      "L'azote encore présent dans les tissus du plongeur après sa remontée, tant qu'il n'a pas été totalement éliminé",
      "L'azote resté dans le bloc de plongée",
      "L'azote produit par l'effort physique",
      "Un terme obsolète qui n'est plus utilisé",
    ],
    correct: 0,
    explanation: "C'est la base du calcul des plongées successives : plus l'intervalle de surface est court, plus l'azote résiduel de la plongée précédente est important au début de la suivante.",
  },
  {
    id: "pla-02", cat: "planification",
    q: "Pourquoi respecter une vitesse de remontée contrôlée et ne jamais remonter trop vite ?",
    choices: [
      "Pour économiser de l'air uniquement",
      "Pour laisser le temps à l'azote dissous de repasser progressivement en phase gazeuse et être éliminé sans former de bulles dangereuses",
      "Pour éviter le froid",
      "Ce n'est qu'une recommandation de confort, sans lien avec la sécurité",
    ],
    correct: 1,
    explanation: "C'est le principe central de la prévention des accidents de décompression. La vitesse exacte recommandée dépend du standard/ordinateur utilisé : réfère-toi à la valeur en vigueur dans ton support SSI.",
  },
  {
    id: "pla-03", cat: "planification",
    q: "Un palier de sécurité (safety stop) sur une plongée sans décompression obligatoire sert à :",
    choices: [
      "Remplacer l'équilibrage des oreilles",
      "Réduire la marge de sécurité en laissant du temps supplémentaire à la désaturation avant la surface",
      "Recharger le bloc en air",
      "Se réchauffer avant la sortie",
    ],
    correct: 1,
    explanation: "Largement recommandé par les organismes de formation (souvent autour de quelques minutes à faible profondeur) comme marge de sécurité supplémentaire — vérifie la durée/profondeur précise préconisée par SSI.",
  },
  {
    id: "pla-04", cat: "planification",
    q: "Pourquoi la plongée en altitude nécessite-t-elle des procédures adaptées ?",
    choices: [
      "L'eau y est toujours plus froide",
      "La pression atmosphérique de référence en surface est plus basse qu'au niveau de la mer, ce qui modifie les calculs de désaturation",
      "Il n'y a pas de différence, les mêmes tables s'appliquent partout",
      "L'oxygène de l'air y est plus concentré",
    ],
    correct: 1,
    explanation: "Une pression de surface plus basse change le rapport de pression entre le fond et la surface : les tables/ordinateurs doivent être adaptés ou réglés en mode altitude.",
  },
  {
    id: "pla-05", cat: "planification",
    q: "Un plus long intervalle de surface entre deux plongées permet :",
    choices: [
      "D'augmenter l'azote résiduel avant la 2e plongée",
      "De réduire davantage l'azote résiduel avant la 2e plongée, laissant plus de marge",
      "De ne plus avoir besoin de palier de sécurité",
      "N'a aucun effet sur la planification",
    ],
    correct: 1,
    explanation: "Plus l'intervalle de surface est long, plus le corps élimine d'azote, ce qui redonne de la marge pour la plongée suivante (plus de temps sans palier, en général).",
  },

  {
    id: "pla-06", cat: "planification",
    q: "En cas de panne d'air totale à faible profondeur, la procédure de remontée d'urgence privilégiée est généralement :",
    choices: [
      "Une remontée contrôlée, si possible assistée par le binôme, en soufflant continuellement pour ne pas bloquer sa respiration",
      "Une apnée complète jusqu'à la surface, poumons bloqués",
      "Une descente pour chercher de l'air ailleurs",
      "Attendre immobile en espérant que l'air revienne",
    ],
    correct: 0,
    explanation: "Le principe fondamental reste de ne jamais bloquer sa respiration en remontant, pour éviter la surpression pulmonaire, tout en remontant le plus posément possible.",
  },
  {
    id: "pla-07", cat: "planification",
    q: "Que peut faire un ordinateur de plongée si un plongeur dépasse gravement les limites qu'il calcule ?",
    choices: [
      "Rien du tout, dans tous les cas",
      "Se verrouiller temporairement sur certains modèles, empêchant l'affichage des données de plongée pendant un délai",
      "Se réinitialiser automatiquement sans conséquence",
      "Prolonger automatiquement l'autonomie en air",
    ],
    correct: 1,
    explanation: "Le comportement exact dépend entièrement du modèle et du fabricant : certains ordinateurs se verrouillent après un dépassement sévère. Vérifie toujours la documentation du modèle utilisé par tes élèves.",
  },
  {
    id: "pla-08", cat: "planification",
    q: "La plongée dite « multi-niveaux » consiste à :",
    choices: [
      "Descendre directement à la profondeur maximale puis y rester tout le temps de la plongée",
      "Profiter d'un profil de plongée qui remonte progressivement par paliers de profondeur au fil du temps, ce qui peut prolonger le temps de plongée sans palier",
      "Faire uniquement des paliers de décompression obligatoires",
      "Une technique réservée à la plongée en altitude",
    ],
    correct: 1,
    explanation: "En remontant progressivement au fil de la plongée plutôt qu'en restant à profondeur constante, on limite l'accumulation d'azote — un principe qu'un ordinateur de plongée gère nativement, contrairement à une table carrée classique.",
  },
  {
    id: "pla-09", cat: "planification",
    q: "Pourquoi de nombreux ordinateurs de plongée intègrent-ils une marge de conservatisme réglable ?",
    choices: [
      "Pour ajouter une sécurité supplémentaire face à la variabilité individuelle (fatigue, froid, âge, condition physique...)",
      "Uniquement pour compliquer l'utilisation de l'appareil",
      "Parce que la loi l'exige dans tous les pays",
      "Cela n'existe sur aucun ordinateur du marché",
    ],
    correct: 0,
    explanation: "Le risque de décompression n'est pas purement mathématique : des facteurs individuels influencent la susceptibilité aux accidents, d'où l'intérêt pédagogique d'expliquer ce réglage à ses élèves.",
  },
  {
    id: "pla-10", cat: "planification",
    q: "En plongée successive, si l'on ne respecte pas un intervalle de surface suffisant, le risque principal est :",
    choices: [
      "D'aborder la 2e plongée avec un azote résiduel plus élevé que prévu, réduisant la marge de sécurité",
      "De consommer plus d'air uniquement",
      "De ne plus pouvoir utiliser son ordinateur",
      "Aucun risque particulier",
    ],
    correct: 0,
    explanation: "C'est pour cette raison que la gestion de l'intervalle de surface est un point clé enseigné dès le niveau Open Water et approfondi en formation d'encadrement.",
  },

  // ---------------- ENVIRONNEMENT & SECURITE ----------------
  {
    id: "env-01", cat: "environnement",
    q: "Face à un courant fort inattendu pendant une plongée encadrée, la priorité de l'instructeur est :",
    choices: [
      "Continuer le programme prévu à l'identique",
      "Regrouper les élèves, garder le contact visuel, et adapter/écourter la plongée si nécessaire pour la sécurité du groupe",
      "Laisser chaque élève se débrouiller seul pour rejoindre la surface",
      "Accélérer la plongée pour finir plus vite",
    ],
    correct: 1,
    explanation: "La gestion de groupe et l'adaptation en temps réel du déroulé sont au cœur des compétences évaluées lors de l'ITC/IE.",
  },
  {
    id: "env-02", cat: "environnement",
    q: "En plongée de nuit, un point de sécurité essentiel à enseigner est :",
    choices: [
      "Ce n'est pas nécessaire d'avoir une lampe de secours",
      "Prévoir un éclairage principal ET un éclairage de secours, et définir des signaux lumineux clairs avant la mise à l'eau",
      "Plonger plus profond qu'en plongée de jour",
      "Se passer de tout signal, la visibilité n'a pas d'importance",
    ],
    correct: 1,
    explanation: "La préparation (matériel de secours, signaux lumineux convenus) est un point pédagogique classique des briefings de plongée de nuit.",
  },
  {
    id: "env-03", cat: "environnement",
    q: "Un thermocline désigne :",
    choices: [
      "Une zone de changement brutal de température dans la colonne d'eau",
      "Un courant de surface uniquement",
      "Un instrument de mesure de la profondeur",
      "Une variation de salinité uniquement",
    ],
    correct: 0,
    explanation: "Utile à expliquer aux élèves pour anticiper l'inconfort thermique et le flou visuel parfois associé au passage d'un thermocline.",
  },
  {
    id: "env-04", cat: "environnement",
    q: "Avant une sortie bateau, un briefing sécurité complet pour des élèves doit notamment couvrir :",
    choices: [
      "Uniquement l'heure de départ",
      "Les procédures de mise à l'eau/remontée à l'échelle, les signaux de rappel, la conduite à tenir en cas de séparation du groupe",
      "Le menu du repas prévu",
      "Rien de particulier, le briefing standard suffit toujours",
    ],
    correct: 1,
    explanation: "Un briefing structuré et complet, adapté au site et aux conditions du jour, est une compétence pédagogique clé évaluée pour un instructeur.",
  },

  {
    id: "env-05", cat: "environnement",
    q: "La plongée dérivante (drift diving) se caractérise par :",
    choices: [
      "Une plongée qui se déroule en se laissant porter par le courant, avec un suivi bateau adapté",
      "Une interdiction totale d'utiliser un bateau",
      "Une plongée toujours réalisée à l'ancre, sans aucun courant",
      "Une technique réservée uniquement à la plongée technique profonde",
    ],
    correct: 0,
    explanation: "Elle demande un briefing spécifique (signal de fin de plongée, suivi de palanquée par le bateau, port éventuel d'un parachute de palier/DSMB) que l'instructeur doit savoir expliquer clairement.",
  },
  {
    id: "env-06", cat: "environnement",
    q: "Face à la vie marine, la bonne pratique générale à enseigner aux élèves est :",
    choices: [
      "Toucher et manipuler les organismes pour mieux les observer",
      "Observer sans toucher ni nourrir, en gardant une distance respectueuse",
      "Collecter des échantillons à chaque plongée",
      "Ignorer complètement l'environnement, ce n'est pas un sujet pédagogique",
    ],
    correct: 1,
    explanation: "La sensibilisation environnementale (ne pas toucher, ne pas nourrir, ne pas abîmer les fonds) fait partie intégrante de la pédagogie moderne de la plongée, dès les premiers niveaux.",
  },
  {
    id: "env-07", cat: "environnement",
    q: "Un DSMB (parachute de palier / marqueur de surface gonflable) sert principalement à :",
    choices: [
      "Signaler la position du plongeur en surface, notamment en plongée dérivante ou en cas de courant",
      "Remplacer le gilet stabilisateur",
      "Servir uniquement de flotteur pour transporter du matériel",
      "Indiquer la profondeur atteinte",
    ],
    correct: 0,
    explanation: "Savoir l'utiliser et l'enseigner correctement (déploiement en fin de plongée ou lors d'un palier) est une compétence de sécurité valorisée dans de nombreux cursus d'encadrement.",
  },
  {
    id: "env-08", cat: "environnement",
    q: "En eau très froide, un point de vigilance supplémentaire pour l'instructeur est :",
    choices: [
      "Le risque de gel/blocage du détendeur en position ouverte (free-flow), en plus du risque d'hypothermie",
      "L'absence totale de risque particulier par rapport à l'eau tempérée",
      "Le fait que le matériel n'a besoin d'aucune adaptation",
      "L'interdiction totale de plonger en dessous de 15°C",
    ],
    correct: 0,
    explanation: "Certains détendeurs standards sont plus sujets au givrage en eau très froide, ce qui fait partie des points à connaître avant d'encadrer ce type d'environnement.",
  },
  {
    id: "env-09", cat: "environnement",
    q: "Un briefing de sécurité avant plongée en carrière ou lac (par rapport à la mer) doit notamment mentionner :",
    choices: [
      "La visibilité souvent réduite, l'absence de courant/marée mais parfois une eau plus froide en profondeur, et les zones réglementées du site",
      "Rien de spécifique, le briefing est strictement identique à la mer",
      "Uniquement la météo du jour",
      "Que la plongée en eau douce ne nécessite jamais de palier de sécurité",
    ],
    correct: 0,
    explanation: "Chaque environnement a ses spécificités (visibilité, thermoclines marqués, absence de courant mais parfois profondeur trompeuse) à intégrer dans un briefing adapté au site.",
  },

  // ---------------- SSI : PARCOURS & PEDAGOGIE ----------------
  {
    id: "ssi-01", cat: "ssi",
    q: "D'après le site officiel SSI (divessi.com), quelle est l'étape qui suit généralement le Divemaster / Dive Control Specialist dans le parcours pro ?",
    choices: [
      "Le Try Scuba",
      "L'Instructor Training Course (ITC)",
      "L'Advanced Adventurer",
      "Le Specialty Diver",
    ],
    correct: 1,
    explanation: "Selon divessi.com, l'ITC est l'étape suivante après le niveau Divemaster/Dive Control Specialist, avant l'évaluation instructeur (IE).",
  },
  {
    id: "ssi-02", cat: "ssi",
    q: "Que doit accomplir un candidat après l'ITC pour devenir officiellement SSI Open Water Instructor ?",
    choices: [
      "Rien, la certification est automatique à la fin de l'ITC",
      "Réussir l'Instructor Evaluation (IE)",
      "Attendre 2 ans d'expérience en tant que Dive Guide",
      "Passer directement Instructor Trainer",
    ],
    correct: 1,
    explanation: "SSI décrit une approche en 2 étapes : ITC puis IE (Instructor Evaluation), à l'issue de laquelle le candidat devient Open Water Instructor.",
  },
  {
    id: "ssi-03", cat: "ssi",
    q: "Le niveau Dive Control Specialist (Dive Con) chez SSI correspond globalement à :",
    choices: [
      "Un niveau de plongeur loisir débutant",
      "Le premier niveau d'encadrement, regroupant les compétences Divemaster et Assistant Instructor",
      "Le niveau le plus élevé, au-dessus d'Instructor Trainer",
      "Une spécialité de plongée technique uniquement",
    ],
    correct: 1,
    explanation: "D'après divessi.com, le Dive Control Specialist est le premier niveau du système de leadership SSI, incluant les compétences Divemaster et Assistant Instructor.",
  },
  {
    id: "ssi-04", cat: "ssi",
    q: "Un SSI Instructor Trainer est qualifié pour :",
    choices: [
      "Uniquement enseigner l'Open Water Diver",
      "Former et encadrer les Instructor Training Courses (ITC) ainsi que les Instructor Crossovers",
      "Seulement plonger en exploration, sans encadrement",
      "Uniquement délivrer des spécialités",
    ],
    correct: 1,
    explanation: "Selon SSI, l'Instructor Trainer conduit les ITC et les Instructor Crossovers, en plus de pouvoir enseigner l'ensemble des cours.",
  },
  {
    id: "ssi-05", cat: "ssi",
    q: "Pendant l'ITC, les futurs instructeurs s'entraînent notamment à enseigner quels programmes (selon divessi.com) ?",
    choices: [
      "Uniquement la spéléologie",
      "L'Open Water Diver et des spécialités comme le Nitrox (Enriched Air), le Diver Stress & Rescue, ou le Perfect Buoyancy",
      "Uniquement des cours pour enfants",
      "Aucun programme spécifique n'est mentionné",
    ],
    correct: 1,
    explanation: "D'après le descriptif officiel SSI de l'ITC : sessions académiques, encadrement en eau confinée, et entraînement à l'enseignement de l'Open Water Diver et de spécialités (Nitrox, Stress & Rescue, Perfect Buoyancy...).",
  },
  {
    id: "ssi-06", cat: "ssi",
    q: "En tant que futur instructeur SSI, quelle affirmation sur les ratios encadrant/élèves est correcte ?",
    choices: [
      "Ils sont universels et jamais rappelés dans les standards",
      "Ils sont fixés par les standards SSI en vigueur et doivent être vérifiés dans le manuel officiel / MySSI, car ils peuvent varier selon le cours et l'environnement",
      "Un instructeur peut toujours encadrer un nombre illimité d'élèves",
      "Les ratios n'existent que pour la plongée technique",
    ],
    correct: 1,
    explanation: "Volontairement, cette appli ne donne pas de chiffre précis de ratio : ces valeurs sont propres aux standards SSI en vigueur et doivent être vérifiées dans tes supports officiels à jour.",
  },
  {
    id: "ssi-07", cat: "ssi",
    q: "Quel est, de façon générale, le rôle central d'un instructeur pendant l'évaluation (IE) ?",
    choices: [
      "Démontrer uniquement ses propres compétences de plongée",
      "Démontrer sa capacité à enseigner, encadrer un groupe et gérer la sécurité, pas seulement ses compétences personnelles de plongeur",
      "Réaliser la plongée la plus profonde possible",
      "Battre un record de temps d'immersion",
    ],
    correct: 1,
    explanation: "L'évaluation d'un instructeur porte sur la pédagogie, la gestion de groupe et la sécurité — bien au-delà du simple niveau de plongée personnel.",
  },
  {
    id: "ssi-08", cat: "ssi",
    q: "En pédagogie de la plongée, la séquence classique « expliquer → démontrer → faire pratiquer → corriger » sert à :",
    choices: [
      "Structurer l'apprentissage d'un geste technique en donnant à l'élève un modèle clair avant qu'il ne s'exerce",
      "Remplacer totalement la théorie académique",
      "N'être utilisée qu'en piscine, jamais en milieu naturel",
      "Éviter d'avoir à corriger les élèves",
    ],
    correct: 0,
    explanation: "C'est un principe général d'apprentissage moteur utilisé dans l'enseignement de la plongée (et de nombreuses disciplines techniques), bien au-delà d'un seul organisme de formation.",
  },
  {
    id: "ssi-09", cat: "ssi",
    q: "Pourquoi un débriefing structuré après chaque séance avec des élèves est-il recommandé ?",
    choices: [
      "Pour faire le point sur ce qui a été réussi, ce qui doit être retravaillé, et fixer des objectifs clairs pour la suite",
      "Uniquement pour remplir une formalité administrative",
      "Parce que cela remplace l'évaluation continue des compétences",
      "Ce n'est utile qu'en fin de formation complète, jamais après une séance",
    ],
    correct: 0,
    explanation: "Le débriefing fait partie intégrante du cycle pédagogique : il renforce l'apprentissage et permet d'ajuster la suite du programme à chaque élève.",
  },
  {
    id: "ssi-10", cat: "ssi",
    q: "Adapter son enseignement au rythme et au niveau de chaque élève (différenciation pédagogique) est important car :",
    choices: [
      "Les élèves progressent à des vitesses différentes, et un même exercice peut être trop facile pour l'un et trop difficile pour l'autre",
      "Tous les élèves apprennent toujours exactement de la même façon",
      "C'est une perte de temps pour l'instructeur",
      "Cela ne concerne que l'enseignement théorique, jamais la pratique",
    ],
    correct: 0,
    explanation: "Un bon instructeur observe, ajuste le rythme et personnalise le feedback plutôt que d'appliquer un déroulé strictement identique à tous les élèves.",
  },
  {
    id: "ssi-11", cat: "ssi",
    q: "Avant la mise à l'eau, une vérification mutuelle du matériel entre binômes (buddy check) permet notamment de :",
    choices: [
      "Repérer des oublis ou anomalies (air coupé, sangle mal fixée, etc.) avant qu'ils ne posent problème sous l'eau",
      "Remplacer le briefing de plongée",
      "N'est utile que pour les plongeurs débutants, jamais pour les moniteurs",
      "Vérifier uniquement l'heure des montres de chacun",
    ],
    correct: 0,
    explanation: "C'est une pratique de sécurité largement enseignée dans les organismes de formation ; les modalités précises (checklist, ordre des vérifications) peuvent varier selon le programme suivi.",
  },
  {
    id: "ssi-12", cat: "ssi",
    q: "Pendant un cours encadré, un instructeur doit en permanence :",
    choices: [
      "Garder une vision d'ensemble du groupe (comptage, position, état de chacun), pas seulement se concentrer sur un élève à la fois",
      "Se concentrer uniquement sur l'élève le plus en difficulté, sans se soucier des autres",
      "Laisser les élèves totalement autonomes dès le premier cours",
      "Rester en surface pendant toute la durée de la plongée encadrée",
    ],
    correct: 0,
    explanation: "La supervision globale du groupe (awareness) est une compétence centrale évaluée lors de la formation instructeur, bien au-delà de la simple exécution technique des exercices.",
  },
  {
    id: "ssi-13", cat: "ssi",
    q: "Selon le portail de formation officiel SSI, le parcours vers Open Water Instructor se résume en 3 grandes étapes. Lesquelles ?",
    choices: [
      "AI (Assistant Instructor) → ITC (Instructor Training Course) → IE (Instructor Evaluation)",
      "Open Water Diver → Advanced → Rescue",
      "Try Scuba → Specialty Diver → Master Diver",
      "Dive Guide → Science of Diving → Nitrox",
    ],
    correct: 0,
    explanation: "C'est la structure confirmée à la fois par le portail officiel training.divessi.com et par plusieurs centres partenaires SSI PRO Instructor Training Center : AI, puis ITC, puis IE.",
  },
  {
    id: "ssi-14", cat: "ssi",
    q: "Parmi les prérequis généralement demandés pour s'inscrire à un Instructor Training Course (ITC) SSI, on trouve notamment :",
    choices: [
      "Être certifié Divemaster (ou équivalent), avoir un nombre minimum de plongées loggées, et une certification Nitrox",
      "N'avoir jamais plongé auparavant",
      "Être uniquement titulaire d'un Open Water Diver, sans autre expérience",
      "Avoir un diplôme universitaire en biologie marine",
    ],
    correct: 0,
    explanation: "D'après le portail officiel SSI : certification Divemaster (ou équivalent), au moins 100 plongées loggées totalisant 65h ou plus, et une certification Nitrox (Enriched Air) — en plus d'un avis médical et d'un certificat de premiers secours à jour. Les valeurs exactes doivent être reconfirmées auprès de ton centre, car un Instructor Trainer peut préciser des points selon le contexte.",
  },
  {
    id: "ssi-15", cat: "ssi",
    q: "Le certificat médical (avis d'aptitude à la plongée signé par un médecin) exigé pour l'ITC doit généralement dater de :",
    choices: [
      "Moins d'un an",
      "Il n'y a aucune limite de validité",
      "Moins de 10 ans",
      "Le jour même de l'examen uniquement",
    ],
    correct: 0,
    explanation: "Selon le portail officiel SSI, un avis médical d'aptitude à la plongée de moins d'un an est généralement requis pour l'ITC — à reconfirmer avec ton centre de formation.",
  },
  {
    id: "ssi-16", cat: "ssi",
    q: "Le certificat de premiers secours / RCP / oxygénothérapie (ex. SSI React Right) exigé pour l'ITC doit généralement avoir été obtenu :",
    choices: [
      "Dans les 24 derniers mois",
      "Il y a plus de 10 ans, sans limite",
      "Le jour de l'inscription uniquement",
      "Cette certification n'est jamais demandée",
    ],
    correct: 0,
    explanation: "Le portail officiel SSI mentionne une validité de 24 mois pour le certificat de premiers secours/RCP/oxygène exigé à l'entrée en ITC — confirmé indépendamment par plusieurs centres partenaires SSI PRO Instructor Training Center.",
  },
  {
    id: "ssi-17", cat: "ssi",
    q: "L'ITC comprend des « Academic Sessions » numérotées (1 à 10 environ). Lequel de ces intitulés en fait bien partie ?",
    choices: [
      "« Overview of SSI » (aperçu de l'organisation SSI)",
      "« Introduction à la spéléologie »",
      "« Histoire des équipements de plongée du 19e siècle »",
      "« Cuisine et nutrition du plongeur »",
    ],
    correct: 0,
    explanation: "Confirmé par le portail officiel SSI : les Academic Sessions de l'ITC incluent notamment « Overview of SSI », « Duties of an SSI Professional », « Program Administration », « The Open Water Diver Program », « Diver Stress & Rescue and Divemaster » et « The Business of Diving », entre autres.",
  },
  {
    id: "ssi-18", cat: "ssi",
    q: "Pendant l'ITC, les « Practical Application Sessions » (ateliers pratiques) servent principalement à :",
    choices: [
      "Mettre en pratique l'enseignement réel de segments de cours (ex. Open Water Diver, Nitrox, Diver Stress & Rescue) sous supervision, avec retours et analyse vidéo",
      "Uniquement passer un examen écrit final",
      "Faire de la plongée loisir sans objectif pédagogique",
      "Remplacer entièrement les sessions académiques théoriques",
    ],
    correct: 0,
    explanation: "Ces ateliers, souvent suivis d'une analyse vidéo et d'un débrief, permettent aux candidats instructeurs de s'entraîner à enseigner de vrais segments de cours avant de le faire seuls avec de vrais élèves.",
  },
];

export const MEMO_CARDS = [
  {
    id: "m-physique",
    cat: "physique",
    title: "Physique — les 3 lois à connaître par cœur",
    bullets: [
      "Boyle-Mariotte : P1·V1 = P2·V2 (température constante) → base de la flottabilité, de la consommation d'air, des barotraumatismes.",
      "Dalton : Ptotale = somme des pressions partielles → base du calcul de MOD en nitrox.",
      "Henry : quantité de gaz dissous ∝ pression partielle → base de toute la théorie de décompression.",
      "Repère usuel : ≈ +1 bar / 10 m d'eau de mer, en plus du bar atmosphérique de surface (à confirmer avec ton support de cours).",
      "Archimède : poussée verticale = poids du volume de fluide déplacé → base de la flottabilité.",
      "Sous l'eau : objets ~25% plus gros/proches (réfraction), rouge absorbé en premier, son ~4x plus rapide que dans l'air, chaleur perdue bien plus vite que dans l'air.",
    ],
  },
  {
    id: "m-physiologie",
    cat: "physiologie",
    title: "Physiologie — accidents à connaître",
    bullets: [
      "Narcose à l'azote : liée à la pression partielle d'azote en profondeur, sensibilité très individuelle.",
      "Accident de décompression (ADD) : remontée trop rapide → bulles d'azote dans les tissus/le sang.",
      "Surpression pulmonaire : blocage respiratoire en remontée → risque d'embolie gazeuse, potentiellement mortel.",
      "Toxicité de l'O2 : risque à pression partielle élevée (nitrox/tech) → calcul systématique de la MOD.",
      "Barotraumatismes : oreilles/sinus (descente), masque (descente), poumons (remontée) — ne jamais forcer une équilibration.",
      "Techniques d'équilibrage : Valsalva, Frenzel — variantes douces à connaître pour dépanner un élève.",
      "Facteurs aggravants d'ADD : alcool, déshydratation, foramen ovale perméable (PFO), fatigue, froid.",
      "Hyperventilation avant apnée : dangereuse, peut provoquer une syncope hypoxique sans signe avant-coureur.",
    ],
  },
  {
    id: "m-materiel",
    cat: "materiel",
    title: "Matériel — fonctions clés",
    bullets: [
      "1er étage : réduit la HP du bloc à une pression intermédiaire stable.",
      "2e étage : délivre l'air à la demande, à la pression ambiante.",
      "SPG (manomètre) : pression restante dans le bloc.",
      "BCD : ajuste la flottabilité (ajout/évacuation d'air).",
      "Néoprène : se compresse avec la profondeur → perte de flottabilité et d'isolation thermique.",
      "Ordinateur de plongée : modélise la charge en azote des tissus à partir du profil réel de la plongée.",
      "Octopus (2e détendeur) : air de secours pour le binôme en panne d'air.",
      "Lest : toujours largable rapidement en cas d'urgence.",
      "Bloc acier vs aluminium : flottabilité différente en fin de plongée (l'alu tend à devenir positif à vide) → ajuste le lestage en conséquence.",
    ],
  },
  {
    id: "m-planification",
    cat: "planification",
    title: "Planification — concepts clés",
    bullets: [
      "Azote résiduel : azote encore présent dans le corps après une plongée, tant qu'il n'est pas totalement éliminé.",
      "Intervalle de surface plus long → plus d'azote éliminé → plus de marge pour la plongée suivante.",
      "Vitesse de remontée contrôlée : indispensable pour laisser l'azote repasser en phase gazeuse en douceur.",
      "Palier de sécurité : marge de sécurité supplémentaire en fin de plongée sans décompression obligatoire.",
      "Plongée en altitude : pression de surface plus basse → procédures/tables adaptées nécessaires.",
      "Plongée multi-niveaux : remonter progressivement pendant la plongée limite l'accumulation d'azote par rapport à un profil « carré ».",
      "Conservatisme réglable sur ordinateur : sécurité supplémentaire face à la variabilité individuelle (froid, âge, fatigue...).",
      "⚠️ Les valeurs précises (durées, profondeurs, vitesses, ratios) doivent être vérifiées dans ton support SSI officiel à jour (manuel, MySSI, ton Instructor Trainer) — volontairement non reproduites ici.",
    ],
  },
  {
    id: "m-environnement",
    cat: "environnement",
    title: "Environnement & sécurité — réflexes d'encadrement",
    bullets: [
      "Courant fort : regrouper le groupe, garder le contact visuel, adapter ou écourter la plongée si besoin.",
      "Plongée de nuit : éclairage principal + secours, signaux lumineux définis avant la mise à l'eau.",
      "Thermocline : anticiper l'inconfort thermique et le flou visuel avec les élèves.",
      "Briefing bateau : procédures de mise à l'eau/remontée, signaux de rappel, conduite en cas de séparation.",
      "Gestion d'un élève en essoufflement : stabiliser, contact visuel/physique, ralentir la respiration, stopper l'effort.",
      "DSMB (parachute de palier) : signale la position en surface, utile en dérivante ou en cas de courant.",
      "Vie marine : observer sans toucher ni nourrir.",
      "Eau froide : risque de givrage (free-flow) des détendeurs, en plus de l'hypothermie.",
    ],
  },
  {
    id: "m-pedagogie",
    cat: "ssi",
    title: "Pédagogie & encadrement — principes généraux",
    bullets: [
      "Séquence d'apprentissage d'un geste technique : expliquer → démontrer → faire pratiquer → corriger.",
      "Débriefing après chaque séance : ce qui est réussi, ce qui est à retravailler, objectifs pour la suite.",
      "Différenciation : adapter rythme et exercices au niveau réel de chaque élève, pas un déroulé unique pour tous.",
      "Vérification mutuelle du matériel (buddy check) avant la mise à l'eau : repérer les oublis/anomalies en amont.",
      "Supervision de groupe (awareness) : garder une vision d'ensemble, pas seulement se concentrer sur un élève à la fois.",
      "⚠️ Ce sont des principes pédagogiques généraux ; les procédures/checklists précises de ton organisme peuvent avoir leur propre formalisation à connaître en plus.",
    ],
  },
  {
    id: "m-ssi",
    cat: "ssi",
    title: "Parcours SSI — repères (source : portail officiel training.divessi.com + centres partenaires)",
    bullets: [
      "Loisir → pro : Open Water Diver → Advanced Adventurer/spécialités → Dive Guide / Science of Diving → Divemaster.",
      "Vers l'instructorat, 3 étapes : AI (Assistant Instructor) → ITC (Instructor Training Course) → IE (Instructor Evaluation) → SSI Open Water Instructor.",
      "Prérequis courants pour l'ITC (à reconfirmer avec ton centre) : Divemaster certifié, ~100 plongées loggées (65h+), certification Nitrox, avis médical de moins d'1 an, certificat premiers secours/RCP/O2 de moins de 24 mois.",
      "Academic Sessions de l'ITC (10 sessions numérotées) : Overview of SSI, Duties of an SSI Professional, Program Administration, Academic Sessions, In-Water Teaching, Assistant Instructor Programs, The Open Water Diver Program, Open Water Instructor Specialties, Diver Stress & Rescue and Divemaster, The Business of Diving.",
      "Practical Application Sessions : ateliers où le candidat enseigne réellement des segments de cours (OWD, Nitrox, Stress & Rescue...) sous supervision, avec analyse vidéo et débrief.",
      "Un Open Water Instructor peut ensuite évoluer vers Specialty Instructor, puis Instructor Trainer (habilité à conduire des ITC et Instructor Crossovers).",
      "⚠️ Structure et prérequis confirmés sur le portail officiel SSI et recoupés avec plusieurs centres partenaires SSI PRO (2026) — les standards évoluent et un Instructor Trainer peut préciser des points : reconfirme toujours auprès de ton centre.",
    ],
  },
  {
    id: "m-disclaimer",
    cat: "ssi",
    title: "⚠️ À lire avant de réviser",
    bullets: [
      "Cette application est un outil de révision PERSONNEL, créé indépendamment. Elle n'est pas éditée, vérifiée ni approuvée officiellement par SSI (Scuba Schools International).",
      "Les questions de physique/physiologie/matériel reflètent des connaissances générales communes à tous les organismes de plongée.",
      "Pour toute donnée chiffrée précise (ratios, procédures d'examen, tables, standards), réfère-toi TOUJOURS à ton SSI Instructor Manual, à MySSI et à ton Instructor Trainer — ce sont les seules sources qui font foi.",
      "En cas de doute sur un point de sécurité, ne te fie jamais uniquement à cette appli.",
    ],
  },
  {
    id: "m-sources",
    cat: "ssi",
    title: "🔎 Comment ce contenu a été vérifié",
    bullets: [
      "Chaque fait de physique/physiologie/sécurité a été recoupé avec au moins 2 sources indépendantes et reconnues : DAN (Divers Alert Network), Merck Manual, NCBI/PubMed, ou sites officiels des organismes de plongée.",
      "La structure du parcours SSI a été vérifiée sur le site officiel divessi.com et recoupée avec d'autres centres de formation SSI indépendants.",
      "La liste complète des sources et liens utilisés est dans le fichier SOURCES.md du dépôt du projet.",
      "Cette vérification réduit fortement le risque d'erreur mais n'a pas été relue par un professionnel de santé de plongée ni un Instructor Trainer SSI — ce n'est pas une garantie absolue.",
    ],
  },
];
